package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"bytes"
	"context"
	"crypto/sha256"

	// "database/sql"
	"encoding/hex"
	"fmt"
	"io"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/aws/aws-sdk-go/aws"

	// "github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/jackc/pgx/v5"
	"github.com/rival231/Balkan_Drive/graph/model"
	"golang.org/x/crypto/bcrypt"
)

// The struct declarations are moved to schema.resolvers.go
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string) (*model.AuthPayload, error) {
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}
	user := &model.User{}
	err = r.DB.QueryRow(ctx, "INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING id, username, email", username, email, string(hashedPassword)).Scan(&user.ID, &user.Username, &user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %v", err)
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"userID": user.ID,
	})
	// In a real application, use a secure key from environment variables or config
	tokenString, err := token.SignedString([]byte("my-secret-key"))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}
	// For simplicity, token generation is omitted
	return &model.AuthPayload{
		Token: tokenString,
		User:  user,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	user := &model.User{}
	err := r.DB.QueryRow(ctx, "SELECT id, username, email, password FROM users WHERE email = $1", email).Scan(&user.ID, &user.Username, &user.Email, &user.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to find user: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(password)); err != nil {
		return nil, fmt.Errorf("invalid password: %v", err)
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"userID": user.ID,
	})
	// In a real application, use a secure key from environment variables or config
	tokenString, err := token.SignedString([]byte("my-secret-key"))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}
	// For simplicity, token generation is omitted
	return &model.AuthPayload{
		Token: tokenString,
		User:  user,
	}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, oldPassword string, newPassword string) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, filename string, filetype string, filePath string, filesize int32, isPublic bool, file graphql.Upload) (*model.UploadIntent, error) {
	// Calculate the hash of the file content
	hash := sha256.New()

	// Create a TeeReader to read file content for both hashing and uploading
	var fileContent bytes.Buffer
	teeReader := io.TeeReader(file.File, &fileContent)

	if _, err := io.Copy(hash, teeReader); err != nil {
		return nil, fmt.Errorf("failed to read file content: %v", err)
	}
	filehash := hex.EncodeToString(hash.Sum(nil))

	// Get the actual file size from the buffer
	actualFileSize := int64(fileContent.Len())

	// ==========================
	// 2. Check if file already exists in `content`
	// ==========================
	var refCount int
	var existingStorageKey string
	err := r.DB.QueryRow(ctx,
		`SELECT ref_count, storage_key FROM content WHERE sha256 = $1`,
		filehash,
	).Scan(&refCount, &existingStorageKey)

	contentExists := err == nil
	if err != nil && err != pgx.ErrNoRows {
		return nil, fmt.Errorf("failed to check content: %v", err)
	}

	// ==========================
	// 3. Initialize S3 client
	// ==========================
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String("eu-north-1"),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create AWS session: %v", err)
	}
	s3Client := s3.New(sess)

	var storageKey string
	var uploadURL string

	if contentExists {
		// File content already exists in database - increment ref_count
		storageKey = existingStorageKey

		_, err = r.DB.Exec(ctx,
			`UPDATE content SET ref_count = ref_count + 1 WHERE sha256 = $1`,
			filehash,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to update ref_count: %v", err)
		}

		// Generate download URL for existing file
		req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
			Bucket: aws.String("go-drive-v2"),
			Key:    aws.String(storageKey),
		})
		uploadURL, err = req.Presign(15 * time.Minute)
		if err != nil {
			return nil, fmt.Errorf("failed to presign download URL: %v", err)
		}

	} else {
		// New file - upload to S3
		storageKey = "uploads/" + filehash

		// ACTUALLY UPLOAD THE FILE TO S3 - Remove ContentLength or use actual size
		_, err = s3Client.PutObject(&s3.PutObjectInput{
			Bucket:      aws.String("go-drive-v2"),
			Key:         aws.String(storageKey),
			Body:        bytes.NewReader(fileContent.Bytes()),
			ContentType: aws.String(filetype),
			// Remove ContentLength - let AWS SDK calculate it automatically
		})
		if err != nil {
			return nil, fmt.Errorf("failed to upload file to S3: %v", err)
		}

		// Generate download URL for the uploaded file
		req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
			Bucket: aws.String("go-drive-v2"),
			Key:    aws.String(storageKey),
		})
		uploadURL, err = req.Presign(15 * time.Minute)
		if err != nil {
			return nil, fmt.Errorf("failed to presign download URL: %v", err)
		}

		// Insert new content record using actual file size
		_, err = r.DB.Exec(ctx,
			`INSERT INTO content (sha256, storage_key, size_bytes, ref_count, created_at)
             VALUES ($1, $2, $3, $4, NOW())`,
			filehash, storageKey, actualFileSize, 1,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to insert content: %v", err)
		}
	}

	// Insert file metadata using actual file size
	var fileRecord model.File
	err = r.DB.QueryRow(ctx,
		`INSERT INTO files (filename, filetype, filesize, filehash, is_public, owner_id, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, NOW())
         RETURNING id, filename, filetype, filesize, filehash, is_public`,
		filename, filetype, actualFileSize, filehash, isPublic, "d92b4a32-3a7e-4542-9076-dcb6e8459c08",
	).Scan(
		&fileRecord.ID,
		&fileRecord.Filename,
		&fileRecord.Filetype,
		&fileRecord.Filesize,
		&fileRecord.Filehash,
		&fileRecord.IsPublic,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to insert file: %v", err)
	}

	return &model.UploadIntent{
		UploadURL:   uploadURL,
		UploadToken: filehash,
	}, nil
}

// CompleteUpload is the resolver for the completeUpload field.
func (r *mutationResolver) CompleteUpload(ctx context.Context, uploadToken string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: CompleteUpload - completeUpload"))
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, fileID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// ChangeVisibility is the resolver for the changeVisibility field.
func (r *mutationResolver) ChangeVisibility(ctx context.Context, fileID string, isPublic bool) (*model.File, error) {
	panic(fmt.Errorf("not implemented: ChangeVisibility - changeVisibility"))
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(ctx context.Context, fileID string, folderID *string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: MoveFile - moveFile"))
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string, parentID *string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, folderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFolder - deleteFolder"))
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, folderID string, newName string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: RenameFolder - renameFolder"))
}

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(ctx context.Context, fileID string, userID string, relationship string) (*model.FileShares, error) {
	panic(fmt.Errorf("not implemented: ShareFile - shareFile"))
}

// UnshareFile is the resolver for the unshareFile field.
func (r *mutationResolver) UnshareFile(ctx context.Context, fileID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnshareFile - unshareFile"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, userID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetFile is the resolver for the getFile field.
func (r *queryResolver) GetFile(ctx context.Context, fileID string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: GetFile - getFile"))
}

// ListFiles is the resolver for the listFiles field.
func (r *queryResolver) ListFiles(ctx context.Context, folder *string, isPublic *bool, ownerID *string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: ListFiles - listFiles"))
}

// SearchFiles is the resolver for the searchFiles field.
func (r *queryResolver) SearchFiles(ctx context.Context, query string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: SearchFiles - searchFiles"))
}

// ListSharedFiles is the resolver for the listSharedFiles field.
func (r *queryResolver) ListSharedFiles(ctx context.Context) ([]*model.FileShares, error) {
	panic(fmt.Errorf("not implemented: ListSharedFiles - listSharedFiles"))
}

// ListFolders is the resolver for the listFolders field.
func (r *queryResolver) ListFolders(ctx context.Context, parentID *string) ([]*model.Folder, error) {
	panic(fmt.Errorf("not implemented: ListFolders - listFolders"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
