package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"context"
	"fmt"

	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/rival231/Balkan_Drive/graph/model"
	"golang.org/x/crypto/bcrypt"
)

// The struct declarations are moved to schema.resolvers.go
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string) (*model.AuthPayload, error) {
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}
	user := &model.User{}
	err = r.DB.QueryRow(ctx, "INSERT INTO users (username, email, password) VALUES ($1, $2, $3) RETURNING id, username, email", username, email, string(hashedPassword)).Scan(&user.ID, &user.Username, &user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %v", err)
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"userID": user.ID,
	})
	// In a real application, use a secure key from environment variables or config
	tokenString, err := token.SignedString([]byte("my-secret-key"))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}
	// For simplicity, token generation is omitted
	return &model.AuthPayload{
		Token: tokenString,
		User:  user,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, oldPassword string, newPassword string) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, filename string, filetype string, filesize int32, isPublic bool) (*model.UploadIntent, error) {
	panic(fmt.Errorf("not implemented: UploadFile - uploadFile"))
}

// CompleteUpload is the resolver for the completeUpload field.
func (r *mutationResolver) CompleteUpload(ctx context.Context, uploadToken string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: CompleteUpload - completeUpload"))
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, fileID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// ChangeVisibility is the resolver for the changeVisibility field.
func (r *mutationResolver) ChangeVisibility(ctx context.Context, fileID string, isPublic bool) (*model.File, error) {
	panic(fmt.Errorf("not implemented: ChangeVisibility - changeVisibility"))
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(ctx context.Context, fileID string, folderID *string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: MoveFile - moveFile"))
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string, parentID *string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, folderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFolder - deleteFolder"))
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, folderID string, newName string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: RenameFolder - renameFolder"))
}

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(ctx context.Context, fileID string, userID string, relationship string) (*model.FileShares, error) {
	panic(fmt.Errorf("not implemented: ShareFile - shareFile"))
}

// UnshareFile is the resolver for the unshareFile field.
func (r *mutationResolver) UnshareFile(ctx context.Context, fileID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnshareFile - unshareFile"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, userID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetFile is the resolver for the getFile field.
func (r *queryResolver) GetFile(ctx context.Context, fileID string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: GetFile - getFile"))
}

// ListFiles is the resolver for the listFiles field.
func (r *queryResolver) ListFiles(ctx context.Context, folder *string, isPublic *bool, ownerID *string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: ListFiles - listFiles"))
}

// SearchFiles is the resolver for the searchFiles field.
func (r *queryResolver) SearchFiles(ctx context.Context, query string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: SearchFiles - searchFiles"))
}

// ListSharedFiles is the resolver for the listSharedFiles field.
func (r *queryResolver) ListSharedFiles(ctx context.Context) ([]*model.FileShares, error) {
	panic(fmt.Errorf("not implemented: ListSharedFiles - listSharedFiles"))
}

// ListFolders is the resolver for the listFolders field.
func (r *queryResolver) ListFolders(ctx context.Context, parentID *string) ([]*model.Folder, error) {
	panic(fmt.Errorf("not implemented: ListFolders - listFolders"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}
func (r *queryResolver) Files(ctx context.Context) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: Files - files"))
}
func (r *queryResolver) Relations(ctx context.Context) ([]*model.Relation, error) {
	panic(fmt.Errorf("not implemented: Relations - relations"))
}
func (r *queryResolver) MyFiles(ctx context.Context) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: MyFiles - myFiles"))
}
*/
