package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"context"
	"fmt"

	"github.com/rival231/Balkan_Drive/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string) (*model.AuthPayload, error) {
	
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, filename string, filetype string, filesize int32, isPublic bool) (*model.UploadIntent, error) {
	panic(fmt.Errorf("not implemented: UploadFile - uploadFile"))
}

// CompleteUpload is the resolver for the completeUpload field.
func (r *mutationResolver) CompleteUpload(ctx context.Context, uploadToken string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: CompleteUpload - completeUpload"))
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, fileID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// ChangeVisibility is the resolver for the changeVisibility field.
func (r *mutationResolver) ChangeVisibility(ctx context.Context, fileID string, isPublic bool) (*model.File, error) {
	panic(fmt.Errorf("not implemented: ChangeVisibility - changeVisibility"))
}

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(ctx context.Context, fileID string, userID string, relationshipType string) (*model.Relation, error) {
	panic(fmt.Errorf("not implemented: ShareFile - shareFile"))
}

// UnshareFile is the resolver for the unshareFile field.
func (r *mutationResolver) UnshareFile(ctx context.Context, fileID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnshareFile - unshareFile"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: Files - files"))
}

// Relations is the resolver for the relations field.
func (r *queryResolver) Relations(ctx context.Context) ([]*model.Relation, error) {
	panic(fmt.Errorf("not implemented: Relations - relations"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// MyFiles is the resolver for the myFiles field.
func (r *queryResolver) MyFiles(ctx context.Context) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: MyFiles - myFiles"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
