# ==========================
# User
# ==========================
type User {
  id: ID!
  username: String!
  email: String!
}

# Used for login/register response
type AuthPayload {
  token: String!
  user: User!
}

# ==========================
# File
# ==========================
type File {
  id: ID!
  filename: String!
  filehash: String!
  filepath: String!
  filetype: String!
  filesize: Int!
  isPublic: Boolean!
  folder: String
  createdAt: String!
  owner: User!
}

# Returned when creating upload
type UploadIntent {
  uploadUrl: String!
  uploadToken: String!
}

# ==========================
# Relations (Sharing)
# ==========================
type FileShares{
  id: ID!
  file: File!
  sharedWith: User!
  permission: String!
  sharedBy: User!
  expiresAt: String!
}

# ==========================
# Queries
# ==========================
type Query {
  # Auth
  me: User!
  getUser(userId: ID!): User


  # File ops
  getFile(fileId: ID!): File
  listFiles(folder: String, isPublic: Boolean, ownerId: ID): [File!]!
  searchFiles(query: String!): [File!]!

  # Sharing
  listSharedFiles: [FileShares!]!

  # Folders
  listFolders(parentId: ID): [Folder!]!

}

type Folder {
  id: ID!
  owner: User!
  name: String!
  parent: Folder
  createdAt: String!
}

# ==========================
# Mutations
# ==========================
type Mutation {
  # Auth
  register(username: String!, email: String!, password: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  changePassword(oldPassword: String!, newPassword: String!): Boolean!


  # File ops
  uploadFile(filename: String!, filetype: String!, filesize: Int!, isPublic: Boolean!): UploadIntent!
  completeUpload(uploadToken: String!): File!
  deleteFile(fileId: ID!): Boolean!
  changeVisibility(fileId: ID!, isPublic: Boolean!): File!
  moveFile(fileId: ID!, folderId: ID): File!
  createFolder(name: String!, parentId: ID): Folder!
  deleteFolder(folderId: ID!): Boolean!
  renameFolder(folderId: ID!, newName: String!): Folder!


  # Sharing
  shareFile(fileId: ID!, userId: ID!, relationship: String!): FileShares!
  unshareFile(fileId: ID!, userId: ID!): Boolean!
 
}
