// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdminStatistics struct {
	TotalUsers           int32              `json:"totalUsers"`
	TotalFiles           int32              `json:"totalFiles"`
	TotalStorage         int32              `json:"totalStorage"`
	TotalSavings         int32              `json:"totalSavings"`
	TotalPublicFiles     int32              `json:"totalPublicFiles"`
	TotalPublicDownloads int32              `json:"totalPublicDownloads"`
	TopDownloadedFiles   []*PublicFileStats `json:"topDownloadedFiles"`
	RecentDownloads      []*FileDownload    `json:"recentDownloads"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Content struct {
	Sha256     string `json:"sha256"`
	StorageKey string `json:"storage_key"`
	SizeBytes  int32  `json:"size_bytes"`
	RefCount   int32  `json:"ref_count"`
	CreatedAt  string `json:"created_at"`
}

type File struct {
	ID                   string  `json:"id"`
	Filename             string  `json:"filename"`
	Filehash             string  `json:"filehash"`
	Filepath             string  `json:"filepath"`
	Filetype             string  `json:"filetype"`
	Filesize             int32   `json:"filesize"`
	IsPublic             bool    `json:"isPublic"`
	IsPublicShared       bool    `json:"isPublicShared"`
	PublicShareEnabledAt *string `json:"publicShareEnabledAt,omitempty"`
	PublicShareEnabledBy *User   `json:"publicShareEnabledBy,omitempty"`
	Folder               *Folder `json:"folder,omitempty"`
	CreatedAt            string  `json:"createdAt"`
	Owner                *User   `json:"owner"`
}

type FileDownload struct {
	ID           string  `json:"id"`
	DownloadedBy *User   `json:"downloadedBy,omitempty"`
	DownloadedAt string  `json:"downloadedAt"`
	IPAddress    *string `json:"ipAddress,omitempty"`
}

type FileDownloadStats struct {
	TotalDownloads int32           `json:"totalDownloads"`
	Downloads      []*FileDownload `json:"downloads"`
}

type FileShares struct {
	ID         string  `json:"id"`
	File       *File   `json:"file,omitempty"`
	SharedWith *User   `json:"sharedWith,omitempty"`
	Permission string  `json:"permission"`
	SharedBy   *User   `json:"sharedBy,omitempty"`
	ExpiresAt  *string `json:"expiresAt,omitempty"`
}

type Folder struct {
	ID        string  `json:"id"`
	Owner     *User   `json:"owner"`
	Name      string  `json:"name"`
	Parent    *Folder `json:"parent,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type MimeTypeFacet struct {
	Type     string `json:"type"`
	Count    int32  `json:"count"`
	Category string `json:"category"`
}

type Mutation struct {
}

type PublicFile struct {
	ID             string `json:"id"`
	Filename       string `json:"filename"`
	Filetype       string `json:"filetype"`
	Filesize       int32  `json:"filesize"`
	CreatedAt      string `json:"createdAt"`
	Owner          *User  `json:"owner"`
	DownloadCount  int32  `json:"downloadCount"`
	PublicSharedAt string `json:"publicSharedAt"`
}

type PublicFileStats struct {
	ID             string `json:"id"`
	Filename       string `json:"filename"`
	DownloadCount  int32  `json:"downloadCount"`
	Owner          *User  `json:"owner"`
	PublicSharedAt string `json:"publicSharedAt"`
}

type Query struct {
}

type SearchFacets struct {
	MimeTypes   []*MimeTypeFacet   `json:"mimeTypes"`
	Uploaders   []*UploaderFacet   `json:"uploaders"`
	SizeBuckets []*SizeBucketFacet `json:"sizeBuckets"`
}

type SearchResult struct {
	Files      []*File       `json:"files"`
	TotalCount int32         `json:"totalCount"`
	HasMore    bool          `json:"hasMore"`
	Facets     *SearchFacets `json:"facets"`
}

type SizeBucketFacet struct {
	Range string `json:"range"`
	Min   int32  `json:"min"`
	Max   *int32 `json:"max,omitempty"`
	Count int32  `json:"count"`
}

type UploadIntent struct {
	UploadURL   string `json:"uploadUrl"`
	UploadToken string `json:"uploadToken"`
}

type UploaderFacet struct {
	Username string `json:"username"`
	UserID   string `json:"userId"`
	Count    int32  `json:"count"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type UserStatistics struct {
	TotalUsed           int32   `json:"totalUsed"`
	OriginalSize        int32   `json:"originalSize"`
	SavingsBytes        int32   `json:"savingsBytes"`
	SavingsPercentage   float64 `json:"savingsPercentage"`
	FileCount           int32   `json:"fileCount"`
	TotalSharedFiles    int32   `json:"totalSharedFiles"`
	TotalReceivedShares int32   `json:"totalReceivedShares"`
}
