// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Content struct {
	Sha256     string `json:"sha256"`
	StorageKey string `json:"storage_key"`
	SizeBytes  int32  `json:"size_bytes"`
	RefCount   int32  `json:"ref_count"`
	CreatedAt  string `json:"created_at"`
}

type File struct {
	ID        string  `json:"id"`
	Filename  string  `json:"filename"`
	Filehash  string  `json:"filehash"`
	Filepath  string  `json:"filepath"`
	Filetype  string  `json:"filetype"`
	Filesize  int32   `json:"filesize"`
	IsPublic  bool    `json:"isPublic"`
	Folder    *Folder `json:"folder,omitempty"`
	CreatedAt string  `json:"createdAt"`
	Owner     *User   `json:"owner"`
}

type FileShares struct {
	ID         string  `json:"id"`
	File       *File   `json:"file"`
	SharedWith *User   `json:"sharedWith"`
	Permission string  `json:"permission"`
	SharedBy   *User   `json:"sharedBy"`
	ExpiresAt  *string `json:"expiresAt,omitempty"`
}

type Folder struct {
	ID        string  `json:"id"`
	Owner     *User   `json:"owner"`
	Name      string  `json:"name"`
	Parent    *Folder `json:"parent,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type UploadIntent struct {
	UploadURL   string `json:"uploadUrl"`
	UploadToken string `json:"uploadToken"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
