// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type File struct {
	ID       string `json:"id"`
	Filename string `json:"filename"`
	Filehash string `json:"filehash"`
	Filepath string `json:"filepath"`
	Filetype string `json:"filetype"`
	Filesize int32  `json:"filesize"`
	Count    int32  `json:"count"`
	IsPublic bool   `json:"isPublic"`
	Owner    *User  `json:"owner"`
}

type Mutation struct {
}

type Query struct {
}

type Relation struct {
	ID               string `json:"id"`
	User             *User  `json:"user"`
	File             *File  `json:"file"`
	RelationshipType string `json:"relationshipType"`
}

type UploadIntent struct {
	UploadURL   string `json:"uploadUrl"`
	UploadToken string `json:"uploadToken"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
