# ==========================
# User
# ==========================
scalar DateTime
scalar Upload
type User {
  id: ID!
  username: String!
  email: String!
  password: String!
  role: String!
}

# Used for login/register response
type AuthPayload {
  token: String!
  user: User!
}
type Folder {
  id: ID!
  owner: User!
  name: String!
  parent: Folder
  createdAt: DateTime!
}
# ==========================
# File
# ==========================
type File {
  id: ID!
  filename: String!
  filehash: String!
  filepath: String!
  filetype: String!
  filesize: Int!
  isPublic: Boolean!
  folder: Folder
  createdAt: DateTime!
  owner: User!
}

type Content{
  sha256: String!
  storage_key: String!
  size_bytes: Int!
  ref_count: Int!
  created_at: DateTime!
}

# Returned when creating upload
type UploadIntent {
  uploadUrl: String!
  uploadToken: String!
}

# ==========================
# Relations (Sharing)
# ==========================
type FileShares{
  id: ID!
  file: File!
  sharedWith: User!
  permission: String!
  sharedBy: User!
  expiresAt: DateTime
}

# ==========================
# Statistics
# ==========================
type StorageStatistics {
  totalUsed: Int!
  originalSize: Int!
  savingsBytes: Int!
  savingsPercentage: Float!
  fileCount: Int!
}

type AdminStatistics {
  totalUsers: Int!
  totalFiles: Int!
  totalStorage: Int!
  totalSavings: Int!
}

# ==========================
# Queries
# ==========================
type Query {
  # Auth
  me: User!
  getUser(userId: ID!): User

  # File ops
  getFile(fileId: ID!): File
  listFiles(folder: String, isPublic: Boolean, ownerId: ID): [File!]!
  searchFiles(query: String!): [File!]!
  getDownloadUrl(fileId: ID!): String!

  # Sharing
  listSharedFiles: [FileShares!]!

  # Folders
  listFolders(parentId: ID): [Folder!]!

  # Statistics
  storageStats: StorageStatistics!
  
  # Admin queries
  adminStats: AdminStatistics!
  listAllUsers: [User!]!
  listAllFiles: [File!]!
}



# ==========================
# Mutations
# ==========================
type Mutation {
  # Auth
  register(username: String!, email: String!, password: String!, role: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  changePassword(oldPassword: String!, newPassword: String!): Boolean!


  # File ops
  uploadFile(filename: String!, filetype: String!, filePath: String!, filesize: Int!, isPublic: Boolean!, file: Upload!): UploadIntent!
  completeUpload(uploadToken: String!): File!
  deleteFile(fileId: ID!): Boolean!
  changeVisibility(fileId: ID!, isPublic: Boolean!): File!
  moveFile(fileId: ID!, folderId: ID): File!
  createFolder(name: String!, parentId: ID): Folder!
  deleteFolder(folderId: ID!): Boolean!
  renameFolder(folderId: ID!, newName: String!): Folder!


  # Sharing
  shareFile(fileId: ID!, userId: ID!, relationship: String!): FileShares!
  shareFileByUsername(fileId: ID!, username: String!, permission: String!): FileShares!
  unshareFile(fileId: ID!, userId: ID!): Boolean!
 
}
