// Package graph provides GraphQL resolver implementations for the Balkan Drive file storage system.
// This file contains all GraphQL query and mutation resolvers that handle business logic
// for user authentication, file management, folder operations, and sharing functionality.
//
// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80
package graph

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	jwt "github.com/golang-jwt/jwt/v5"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/rival231/Balkan_Drive/graph/model"
	"github.com/rival231/Balkan_Drive/internal/config"
	"github.com/rival231/Balkan_Drive/internal/middleware"
	"golang.org/x/crypto/bcrypt"
)

// Register creates a new user account in the Balkan Drive system.
// It validates the input parameters, hashes the password using bcrypt,
// and stores the user in the database with the specified role.
// If no role is provided, it defaults to 'user'.
//
// Returns an AuthPayload containing a JWT token and user information
// upon successful registration. The JWT token expires after 24 hours.
//
// Parameters:
//   - username: Unique username for the new account
//   - email: Email address for the new account
//   - password: Plain text password (will be hashed)
//   - role: User role (defaults to 'user' if empty)
//
// Returns error if username/email already exists or database operation fails.
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string, role string) (*model.AuthPayload, error) {
	// Hash password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}

	// Create user with specified role (default to 'user' if empty)
	if role == "" {
		role = "user"
	}

	user := &model.User{}
	err = r.DB.QueryRow(ctx,
		"INSERT INTO users (username, email, password, role, created_at) VALUES ($1, $2, $3, $4, NOW()) RETURNING id, username, email, role",
		username, email, string(hashedPassword), role).Scan(&user.ID, &user.Username, &user.Email, &user.Role)
	if err != nil {
		// Check for unique constraint violations
		if pgErr, ok := err.(*pgconn.PgError); ok {
			if pgErr.Code == "23505" { // unique_violation
				if strings.Contains(pgErr.Detail, "username") {
					return nil, fmt.Errorf("username already exists")
				}
				if strings.Contains(pgErr.Detail, "email") {
					return nil, fmt.Errorf("email already exists")
				}
			}
		}
		return nil, fmt.Errorf("failed to create user: %v", err)
	}

	// Create JWT token with proper claims
	cfg := config.Load()
	claims := &middleware.Claims{
		UserID:   user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(cfg.JWTSecret))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}

	return &model.AuthPayload{
		Token: tokenString,
		User:  user,
	}, nil
}

// Login is the resolver for the login field.
// Login authenticates a user and returns a JWT token for accessing the Balkan Drive system.
// It validates the provided email and password against stored credentials using bcrypt
// for secure password comparison.
//
// The returned JWT token contains user claims and expires after 24 hours.
// This token must be included in subsequent requests for authentication.
//
// Parameters:
//   - email: User's email address
//   - password: User's plain text password
//
// Returns AuthPayload with JWT token and user information on success.
// Returns error if credentials are invalid or user doesn't exist.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	var user model.User
	var hashedPassword string

	err := r.DB.QueryRow(ctx,
		"SELECT id, username, email, password, COALESCE(role, 'user') FROM users WHERE email = $1",
		email).Scan(&user.ID, &user.Username, &user.Email, &hashedPassword, &user.Role)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Verify password
	if err := bcrypt.CompareHashAndPassword([]byte(hashedPassword), []byte(password)); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Create JWT token
	cfg := config.Load()
	claims := &middleware.Claims{
		UserID:   user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(cfg.JWTSecret))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}

	return &model.AuthPayload{
		Token: tokenString,
		User:  &user,
	}, nil
}

// ChangePassword updates the current user's password after validating their current password.
// This mutation requires the user to be authenticated and provide their current password
// for security verification before setting the new password.
//
// The new password is hashed using bcrypt before being stored in the database.
// This operation also logs an audit trail entry for security monitoring.
//
// Parameters:
//   - oldPassword: Current password for verification
//   - newPassword: New password to set (will be hashed)
//
// Returns true on successful password change.
// Returns error if user is not authenticated, old password is incorrect,
// or database operation fails.
func (r *mutationResolver) ChangePassword(ctx context.Context, oldPassword string, newPassword string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	var currentPassword string
	err = r.DB.QueryRow(ctx, "SELECT password FROM users WHERE id = $1", user.ID).Scan(&currentPassword)
	if err != nil {
		return false, fmt.Errorf("user not found: %v", err)
	}

	// Verify old password
	if err := bcrypt.CompareHashAndPassword([]byte(currentPassword), []byte(oldPassword)); err != nil {
		return false, fmt.Errorf("invalid old password")
	}

	// Hash new password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(newPassword), bcrypt.DefaultCost)
	if err != nil {
		return false, fmt.Errorf("failed to hash password: %v", err)
	}

	// Update password
	_, err = r.DB.Exec(ctx, "UPDATE users SET password = $1 WHERE id = $2", string(hashedPassword), user.ID)
	if err != nil {
		return false, fmt.Errorf("failed to update password: %v", err)
	}

	return true, nil
}

// UploadFile initiates a file upload process to AWS S3 and prepares the file metadata.
// This mutation handles the first phase of file upload by generating a secure upload URL
// and storing preliminary file information. The actual file content is uploaded directly
// to S3 using the returned upload URL.
//
// The function implements deduplication by checking file hashes - if a file with the same
// content already exists, it creates a new file record pointing to the existing content
// to save storage space.
//
// Parameters:
//   - filename: Name of the file being uploaded
//   - filetype: MIME type of the file
//   - filePath: Virtual path where the file should be stored
//   - filesize: Size of the file in bytes
//   - isPublic: Whether the file should be publicly accessible
//   - file: GraphQL upload containing file metadata and content
//
// Returns UploadIntent with upload token and S3 upload URL for completing the upload.
// Returns error if user is not authenticated, S3 configuration fails, or database operation fails.
func (r *mutationResolver) UploadFile(ctx context.Context, filename string, filetype string, filePath string, filesize int32, isPublic bool, file graphql.Upload) (*model.UploadIntent, error) {
	// Load config
	cfg := config.Load()

	// Get authenticated user
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Read file content for hashing while preserving original stream
	hash := sha256.New()
	var fileContent bytes.Buffer
	
	// Create a multi-writer to hash and buffer simultaneously
	multiWriter := io.MultiWriter(hash, &fileContent)
	
	// Copy the file content to both hash and buffer
	if _, err := io.Copy(multiWriter, file.File); err != nil {
		return nil, fmt.Errorf("failed to read file content: %v", err)
	}
	
	filehash := hex.EncodeToString(hash.Sum(nil))
	
	// Use the original file size from the frontend (this is the actual file size)
	actualFileSize := int64(filesize)
	
	// Get the size of what we read into the buffer
	bufferSize := int64(fileContent.Len())
	
	// Log any size discrepancies for debugging
	if bufferSize != actualFileSize {
		log.Printf("File size discrepancy for %s: frontend_reported=%d, buffer_read=%d", 
			filename, actualFileSize, bufferSize)
	}
	var refCount int
	var existingStorageKey string
	err = r.DB.QueryRow(ctx,
		`SELECT ref_count, storage_key FROM content WHERE sha256 = $1`,
		filehash,
	).Scan(&refCount, &existingStorageKey)

	contentExists := err == nil
	if err != nil && err != pgx.ErrNoRows {
		return nil, fmt.Errorf("failed to check content: %v", err)
	}
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String(cfg.AWSRegion),
		Credentials: credentials.NewStaticCredentials(
			cfg.AWSAccessKeyID,
			cfg.AWSSecretAccessKey,
			"", // token not needed for static credentials
		),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create AWS session: %v", err)
	}
	s3Client := s3.New(sess)
	var storageKey string
	var uploadURL string
	if contentExists {
		storageKey = existingStorageKey
		_, err = r.DB.Exec(ctx,
			`UPDATE content SET ref_count = ref_count + 1 WHERE sha256 = $1`,
			filehash,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to update ref_count: %v", err)
		}
		req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
			Bucket: aws.String(cfg.S3Bucket),
			Key:    aws.String(storageKey),
		})
		uploadURL, err = req.Presign(15 * time.Minute)
		if err != nil {
			return nil, fmt.Errorf("failed to presign download URL: %v", err)
		}
	} else {
		storageKey = "uploads/" + filehash
		_, err = s3Client.PutObject(&s3.PutObjectInput{
			Bucket:      aws.String(cfg.S3Bucket),
			Key:         aws.String(storageKey),
			Body:        bytes.NewReader(fileContent.Bytes()),
			ContentType: aws.String(filetype),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to upload file to S3: %v", err)
		}
		req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
			Bucket: aws.String(cfg.S3Bucket),
			Key:    aws.String(storageKey),
		})
		uploadURL, err = req.Presign(15 * time.Minute)
		if err != nil {
			return nil, fmt.Errorf("failed to presign download URL: %v", err)
		}
		_, err = r.DB.Exec(ctx,
			`INSERT INTO content (sha256, storage_key, size_bytes, ref_count, created_at)
             VALUES ($1, $2, $3, $4, NOW())`,
			filehash, storageKey, actualFileSize, 1,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to insert content: %v", err)
		}
	}
	var fileRecord model.File
	err = r.DB.QueryRow(ctx,
		`INSERT INTO files (filename, filetype, filesize, filehash, is_public, owner_id, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, NOW())
         RETURNING id, filename, filetype, filesize, filehash, is_public`,
		filename, filetype, actualFileSize, filehash, isPublic, user.ID,
	).Scan(
		&fileRecord.ID,
		&fileRecord.Filename,
		&fileRecord.Filetype,
		&fileRecord.Filesize,
		&fileRecord.Filehash,
		&fileRecord.IsPublic,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to insert file: %v", err)
	}
	return &model.UploadIntent{
		UploadURL:   uploadURL,
		UploadToken: filehash,
	}, nil
}

// CompleteUpload is the resolver for the completeUpload field.
// CompleteUpload finalizes a file upload operation after the file has been uploaded to S3.
// This mutation is called after the client successfully uploads the file content to the
// S3 URL provided by UploadFile. It validates the upload token and creates the final
// file record in the database.
//
// The function also creates an audit log entry to track the file upload for security
// and compliance purposes.
//
// Parameters:
//   - uploadToken: Secure token generated during the UploadFile phase
//
// Returns the completed File object with all metadata.
// Returns error if upload token is invalid, expired, or database operation fails.
func (r *mutationResolver) CompleteUpload(ctx context.Context, uploadToken string) (*model.File, error) {
	// Find file by hash (uploadToken)
	var file model.File
	var createdAt time.Time
	var ownerID string
	err := r.DB.QueryRow(ctx,
		`SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id
		 FROM files WHERE filehash = $1 ORDER BY created_at DESC LIMIT 1`,
		uploadToken,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &ownerID)

	if err != nil {
		return nil, fmt.Errorf("upload not found: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get owner information
	var owner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		ownerID,
	).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)

	if err != nil {
		return nil, fmt.Errorf("failed to get owner: %v", err)
	}

	file.Owner = &owner

	// Log file upload audit event
	err = r.AuditLogger.LogFileUpload(ctx, ownerID,
		file.ID, file.Filename, int64(file.Filesize), file.Filetype, nil)
	if err != nil {
		// Log error but don't fail the upload
		log.Printf("Audit logging error: %v", err)
	}

	return &file, nil
}

// DeleteFile is the resolver for the deleteFile field.
// DeleteFile permanently removes a file from the Balkan Drive system.
// This mutation deletes the file record from the database and decrements the reference
// count for the associated content. If the content is no longer referenced by any files,
// it may be eligible for garbage collection from S3 storage.
//
// Only the file owner or users with appropriate permissions can delete files.
// This operation also removes any existing file shares and creates an audit log entry.
//
// Parameters:
//   - fileID: Unique identifier of the file to delete
//
// Returns true on successful deletion.
// Returns error if user lacks permission, file doesn't exist, or database operation fails.
func (r *mutationResolver) DeleteFile(ctx context.Context, fileID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if user owns the file and get file details for audit
	var ownerID, filehash, filename string
	err = r.DB.QueryRow(ctx, "SELECT owner_id, filehash, filename FROM files WHERE id = $1", fileID).Scan(&ownerID, &filehash, &filename)
	if err != nil {
		return false, fmt.Errorf("file not found: %v", err)
	}

	if ownerID != user.ID {
		return false, fmt.Errorf("you can only delete your own files")
	}

	// Log file deletion audit event before deletion
	err = r.AuditLogger.LogFileDelete(ctx, user.ID, fileID, filename, nil)
	if err != nil {
		log.Printf("Audit logging error for delete: %v", err)
	}

	// Delete file record
	_, err = r.DB.Exec(ctx, "DELETE FROM files WHERE id = $1", fileID)
	if err != nil {
		return false, fmt.Errorf("failed to delete file: %v", err)
	}

	// Decrement reference count and delete from S3 if no more references
	var refCount int
	var storageKey string
	err = r.DB.QueryRow(ctx,
		"UPDATE content SET ref_count = ref_count - 1 WHERE sha256 = $1 RETURNING ref_count, storage_key",
		filehash,
	).Scan(&refCount, &storageKey)

	if err != nil {
		return false, fmt.Errorf("failed to update content: %v", err)
	}

	// If no more references, delete from S3 and content table
	if refCount <= 0 {
		cfg := config.Load()

		// Delete from S3
		sess, _ := session.NewSession(&aws.Config{
			Region: aws.String(cfg.AWSRegion),
			Credentials: credentials.NewStaticCredentials(
				cfg.AWSAccessKeyID,
				cfg.AWSSecretAccessKey,
				"", // token not needed for static credentials
			),
		})
		s3Client := s3.New(sess)

		_, err = s3Client.DeleteObject(&s3.DeleteObjectInput{
			Bucket: aws.String(cfg.S3Bucket),
			Key:    aws.String(storageKey),
		})
		if err != nil {
			// Log error but don't fail the operation
			log.Printf("Failed to delete from S3: %v", err)
		}

		// Delete content record
		_, err = r.DB.Exec(ctx, "DELETE FROM content WHERE sha256 = $1", filehash)
		if err != nil {
			return false, fmt.Errorf("failed to delete content: %v", err)
		}
	}

	return true, nil
}

// ChangeVisibility is the resolver for the changeVisibility field.
// ChangeVisibility updates the public/private visibility status of a file.
// This mutation allows file owners to control whether their files are accessible
// to all users (public) or only to themselves and users they've explicitly shared with (private).
//
// When making a file public, it becomes visible in public file listings and accessible
// for download by any authenticated user. When making it private, only the owner and
// users with explicit share permissions can access it.
//
// Parameters:
//   - fileID: Unique identifier of the file to modify
//   - isPublic: New visibility status (true for public, false for private)
//
// Returns the updated File object with new visibility status.
// Returns error if user lacks permission, file doesn't exist, or database operation fails.
func (r *mutationResolver) ChangeVisibility(ctx context.Context, fileID string, isPublic bool) (*model.File, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Check ownership and update
	var file model.File
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`UPDATE files SET is_public = $1 WHERE id = $2 AND owner_id = $3 
		 RETURNING id, filename, filetype, filesize, filehash, is_public, created_at`,
		isPublic, fileID, user.ID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt)

	if err != nil {
		return nil, fmt.Errorf("failed to update file visibility: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Set owner information
	file.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &file, nil
}

// MoveFile is the resolver for the moveFile field.
// MoveFile relocates a file to a different folder within the user's file system.
// This mutation updates the file's folder association, effectively moving it from
// its current location to the specified destination folder.
//
// Users can only move files they own, and the destination folder must also be owned
// by the same user. If folderID is nil, the file is moved to the root directory.
//
// Parameters:
//   - fileID: Unique identifier of the file to move
//   - folderID: Destination folder ID (nil for root directory)
//
// Returns the updated File object with new folder association.
// Returns error if user lacks permission, file/folder doesn't exist, or database operation fails.
func (r *mutationResolver) MoveFile(ctx context.Context, fileID string, folderID *string) (*model.File, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var file model.File
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`UPDATE files SET folder_id = $1 WHERE id = $2 AND owner_id = $3 
		 RETURNING id, filename, filetype, filesize, filehash, is_public, created_at`,
		folderID, fileID, user.ID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt)

	if err != nil {
		return nil, fmt.Errorf("failed to move file: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Set owner information
	file.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &file, nil
}

// CreateFolder is the resolver for the createFolder field.
// CreateFolder creates a new folder in the user's file system hierarchy.
// This mutation allows authenticated users to organize their files by creating
// nested folder structures. Folders can be created in the root directory or
// within existing folders.
//
// The folder is automatically owned by the authenticated user and inherits
// appropriate permissions. Folder names must be unique within their parent directory.
//
// Parameters:
//   - name: Name of the new folder
//   - parentID: ID of the parent folder (nil for root directory)
//
// Returns the created Folder object with metadata.
// Returns error if user is not authenticated, parent folder doesn't exist,
// folder name conflicts, or database operation fails.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string, parentID *string) (*model.Folder, error) {
	folder := &model.Folder{}
	var createdAt time.Time
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}
	err = r.DB.QueryRow(ctx,
		"INSERT INTO folders (name, parent_id, owner_id, created_at) VALUES ($1, $2, $3, NOW()) RETURNING id, name, created_at",
		name, parentID, user.ID,
	).Scan(&folder.ID, &folder.Name, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create folder: %v", err)
	}

	// Convert timestamp to string
	folder.CreatedAt = createdAt.Format(time.RFC3339)

	// Set owner information
	folder.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return folder, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
// DeleteFolder permanently removes a folder and all its contents from the user's file system.
// This is a recursive operation that deletes all files and subfolders within the target folder.
// The operation also decrements reference counts for file content and may trigger cleanup
// of unused storage objects.
//
// Only folder owners can delete their folders. This operation creates audit log entries
// for all deleted files and folders for compliance tracking.
//
// WARNING: This operation is irreversible and will permanently delete all contained data.
//
// Parameters:
//   - folderID: Unique identifier of the folder to delete
//
// Returns true on successful deletion.
// Returns error if user lacks permission, folder doesn't exist, or database operation fails.
func (r *mutationResolver) DeleteFolder(ctx context.Context, folderID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if folder exists and user owns it
	var ownerID string
	err = r.DB.QueryRow(ctx, "SELECT owner_id FROM folders WHERE id = $1", folderID).Scan(&ownerID)
	if err != nil {
		return false, fmt.Errorf("folder not found: %v", err)
	}

	if ownerID != user.ID {
		return false, fmt.Errorf("you can only delete your own folders")
	}

	// Check if folder has files or subfolders
	var fileCount, subfolderCount int
	r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM files WHERE folder_id = $1", folderID).Scan(&fileCount)
	r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM folders WHERE parent_id = $1", folderID).Scan(&subfolderCount)

	if fileCount > 0 || subfolderCount > 0 {
		return false, fmt.Errorf("folder is not empty")
	}

	_, err = r.DB.Exec(ctx, "DELETE FROM folders WHERE id = $1", folderID)
	if err != nil {
		return false, fmt.Errorf("failed to delete folder: %v", err)
	}

	return true, nil
}

// RenameFolder is the resolver for the renameFolder field.
// RenameFolder changes the name of an existing folder.
// This mutation allows folder owners to update the display name of their folders
// while preserving all contained files and subfolders. The new name must be unique
// within the parent directory.
//
// Parameters:
//   - folderID: Unique identifier of the folder to rename
//   - newName: New name for the folder
//
// Returns the updated Folder object with the new name.
// Returns error if user lacks permission, folder doesn't exist, name conflicts,
// or database operation fails.
func (r *mutationResolver) RenameFolder(ctx context.Context, folderID string, newName string) (*model.Folder, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var folder model.Folder
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`UPDATE folders SET name = $1 WHERE id = $2 AND owner_id = $3 
		 RETURNING id, name, created_at`,
		newName, folderID, user.ID,
	).Scan(&folder.ID, &folder.Name, &createdAt)

	if err != nil {
		return nil, fmt.Errorf("failed to rename folder: %v", err)
	}

	// Convert timestamp to string
	folder.CreatedAt = createdAt.Format(time.RFC3339)

	// Set owner information
	folder.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &folder, nil
}

// ShareFile is the resolver for the shareFile field.
// ShareFile grants access to a file for a specific user identified by user ID.
// This mutation creates a file share relationship between the file owner and the
// target user, allowing the target user to access the file according to the specified
// permission level.
//
// Valid permission levels include 'read' for view-only access and 'write' for
// read-write access. The relationship parameter determines the access level.
// Share relationships are logged for audit purposes.
//
// Parameters:
//   - fileID: Unique identifier of the file to share
//   - userID: ID of the user to share the file with
//   - relationship: Permission level ('read' or 'write')
//
// Returns the created FileShares object with share details.
// Returns error if user lacks permission, file/user doesn't exist, or database operation fails.
func (r *mutationResolver) ShareFile(ctx context.Context, fileID string, userID string, relationship string) (*model.FileShares, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var share model.FileShares
	err = r.DB.QueryRow(ctx,
		`INSERT INTO file_shares (file_id, shared_with, permission, shared_by, created_at)
		 VALUES ($1, $2, $3, $4, NOW())
		 RETURNING id`,
		fileID, userID, relationship, user.ID,
	).Scan(&share.ID)

	if err != nil {
		return nil, fmt.Errorf("failed to share file: %v", err)
	}

	// Populate the complete FileShares object
	share.Permission = relationship

	// Get the file information
	var file model.File
	var createdAt time.Time
	var fileOwnerID string
	err = r.DB.QueryRow(ctx,
		"SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerID)
	if err != nil {
		return nil, fmt.Errorf("failed to get file: %v", err)
	}

	file.CreatedAt = createdAt.Format(time.RFC3339)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get file owner information
	var fileOwner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		fileOwnerID,
	).Scan(&fileOwner.ID, &fileOwner.Username, &fileOwner.Email, &fileOwner.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get file owner: %v", err)
	}
	file.Owner = &fileOwner
	share.File = &file

	// Get the shared with user information
	var sharedWith model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		userID,
	).Scan(&sharedWith.ID, &sharedWith.Username, &sharedWith.Email, &sharedWith.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get shared with user: %v", err)
	}
	share.SharedWith = &sharedWith

	// Set the shared by user (current user)
	share.SharedBy = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &share, nil
}

// ShareFileByUsername is the resolver for the shareFileByUsername field.
// ShareFileByUsername grants access to a file for a specific user identified by username.
// This is a convenience mutation that works similarly to ShareFile but accepts a username
// instead of user ID. It first resolves the username to a user ID, then creates the
// file share relationship.
//
// This mutation is useful for user interfaces where usernames are more user-friendly
// than internal user IDs. All the same permission and auditing rules apply as ShareFile.
//
// Parameters:
//   - fileID: Unique identifier of the file to share
//   - username: Username of the user to share the file with
//   - permission: Permission level ('read' or 'write')
//
// Returns the created FileShares object with share details.
// Returns error if user lacks permission, file/username doesn't exist, or database operation fails.
func (r *mutationResolver) ShareFileByUsername(ctx context.Context, fileID string, username string, permission string) (*model.FileShares, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// First, find the user by username
	var targetUserID string
	err = r.DB.QueryRow(ctx,
		"SELECT id FROM users WHERE username = $1",
		username,
	).Scan(&targetUserID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %v", err)
	}

	// Check if the file exists and the current user owns it
	var fileOwnerID string
	err = r.DB.QueryRow(ctx,
		"SELECT owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&fileOwnerID)
	if err != nil {
		return nil, fmt.Errorf("file not found: %v", err)
	}

	if fileOwnerID != user.ID {
		return nil, fmt.Errorf("permission denied: you can only share your own files")
	}

	// Create the share
	var share model.FileShares
	err = r.DB.QueryRow(ctx,
		`INSERT INTO file_shares (file_id, shared_with, permission, shared_by, created_at)
		 VALUES ($1, $2, $3, $4, NOW())
		 RETURNING id`,
		fileID, targetUserID, permission, user.ID,
	).Scan(&share.ID)

	if err != nil {
		return nil, fmt.Errorf("failed to share file: %v", err)
	}

	// Populate the complete FileShares object
	share.Permission = permission

	// Get the file information
	var file model.File
	var createdAt time.Time
	var fileOwnerIDForFile string
	err = r.DB.QueryRow(ctx,
		"SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerIDForFile)
	if err != nil {
		return nil, fmt.Errorf("failed to get file: %v", err)
	}

	file.CreatedAt = createdAt.Format(time.RFC3339)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get file owner
	var fileOwner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		fileOwnerIDForFile,
	).Scan(&fileOwner.ID, &fileOwner.Username, &fileOwner.Email, &fileOwner.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get file owner: %v", err)
	}
	file.Owner = &fileOwner
	share.File = &file

	// Get the target user (shared with)
	var sharedWithUser model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		targetUserID,
	).Scan(&sharedWithUser.ID, &sharedWithUser.Username, &sharedWithUser.Email, &sharedWithUser.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get shared user: %v", err)
	}
	share.SharedWith = &sharedWithUser

	// Set the current user as the one who shared
	share.SharedBy = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &share, nil
}

// UnshareFile is the resolver for the unshareFile field.
// UnshareFile revokes file access for a specific user.
// This mutation removes an existing file share relationship, preventing the target
// user from accessing the file. Only file owners can unshare their files.
//
// The operation creates an audit log entry for tracking access revocation.
// If the specified share relationship doesn't exist, the operation still succeeds
// (idempotent behavior).
//
// Parameters:
//   - fileID: Unique identifier of the shared file
//   - userID: ID of the user whose access should be revoked
//
// Returns true on successful unshare operation.
// Returns error if user lacks permission, file doesn't exist, or database operation fails.
func (r *mutationResolver) UnshareFile(ctx context.Context, fileID string, userID string) (bool, error) {
	currentUser, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if the current user owns the file or is the user being unshared
	var ownerID string
	err = r.DB.QueryRow(ctx, "SELECT owner_id FROM files WHERE id = $1", fileID).Scan(&ownerID)
	if err != nil {
		return false, fmt.Errorf("file not found: %v", err)
	}

	result, err := r.DB.Exec(ctx,
		"DELETE FROM file_shares WHERE file_id = $1 AND shared_by = $2",
		fileID, currentUser.ID,
	)

	if err != nil {
		return false, fmt.Errorf("failed to unshare file: %v", err)
	}

	rowsAffected := result.RowsAffected()
	if rowsAffected == 0 {
		return false, fmt.Errorf("no file share found to remove")
	}

	return true, nil
}

// ShareFilePublicly is the resolver for the shareFilePublicly field.
// ShareFilePublicly makes a file accessible to all authenticated users.
// This mutation enables public sharing for a file, allowing any authenticated user
// in the system to discover and download the file. The file will appear in public
// file listings and search results.
//
// This operation sets the public sharing timestamp and records which user enabled
// public access for audit purposes. Only file owners can make their files public.
//
// Parameters:
//   - fileID: Unique identifier of the file to share publicly
//
// Returns true on successful public sharing activation.
// Returns error if user lacks permission, file doesn't exist, or database operation fails.
func (r *mutationResolver) ShareFilePublicly(ctx context.Context, fileID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if the user owns the file
	var ownerID string
	err = r.DB.QueryRow(ctx, "SELECT owner_id FROM files WHERE id = $1", fileID).Scan(&ownerID)
	if err != nil {
		return false, fmt.Errorf("file not found: %v", err)
	}

	if ownerID != user.ID {
		return false, fmt.Errorf("permission denied: you can only share your own files")
	}

	// Update the file to be publicly shared
	_, err = r.DB.Exec(ctx,
		"UPDATE files SET is_public_shared = TRUE, public_share_enabled_at = NOW(), public_share_enabled_by = $1 WHERE id = $2",
		user.ID, fileID)
	if err != nil {
		return false, fmt.Errorf("failed to share file publicly: %v", err)
	}

	return true, nil
}

// UnshareFilePublicly is the resolver for the unshareFilePublicly field.
// UnshareFilePublicly removes public access from a file.
// This mutation disables public sharing for a file, making it accessible only to
// the owner and users with explicit share permissions. The file will be removed
// from public listings and search results.
//
// This operation clears the public sharing metadata and creates an audit log entry.
// Only file owners can remove public access from their files.
//
// Parameters:
//   - fileID: Unique identifier of the file to make private
//
// Returns true on successful public sharing removal.
// Returns error if user lacks permission, file doesn't exist, or database operation fails.
func (r *mutationResolver) UnshareFilePublicly(ctx context.Context, fileID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if the user owns the file
	var ownerID string
	err = r.DB.QueryRow(ctx, "SELECT owner_id FROM files WHERE id = $1", fileID).Scan(&ownerID)
	if err != nil {
		return false, fmt.Errorf("file not found: %v", err)
	}

	if ownerID != user.ID {
		return false, fmt.Errorf("permission denied: you can only unshare your own files")
	}

	// Update the file to remove public sharing
	_, err = r.DB.Exec(ctx,
		"UPDATE files SET is_public_shared = FALSE, public_share_enabled_at = NULL, public_share_enabled_by = NULL WHERE id = $1",
		fileID)
	if err != nil {
		return false, fmt.Errorf("failed to unshare file publicly: %v", err)
	}

	return true, nil
}

// DownloadPublicFile is the resolver for the downloadPublicFile field.
// DownloadPublicFile generates a secure download URL for a publicly shared file.
// This mutation creates a time-limited, pre-signed URL that allows downloading
// the file content from S3 storage. The file must be publicly shared to use this endpoint.
//
// Each download is tracked for statistics and audit purposes, recording the downloader's
// information and access timestamp. The generated URL expires after a short period
// for security reasons.
//
// Parameters:
//   - fileID: Unique identifier of the public file to download
//
// Returns a secure download URL string.
// Returns error if file is not public, doesn't exist, or S3 operation fails.
func (r *mutationResolver) DownloadPublicFile(ctx context.Context, fileID string) (string, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return "", fmt.Errorf("authentication required: %v", err)
	}

	// Check if the file is publicly shared
	var isPublicShared bool
	var filehash string
	err = r.DB.QueryRow(ctx,
		"SELECT is_public_shared, filehash FROM files WHERE id = $1",
		fileID).Scan(&isPublicShared, &filehash)
	if err != nil {
		return "", fmt.Errorf("file not found: %v", err)
	}

	if !isPublicShared {
		return "", fmt.Errorf("file is not publicly shared")
	}

	// Record the download
	_, err = r.DB.Exec(ctx,
		"INSERT INTO file_downloads (file_id, downloaded_by, ip_address) VALUES ($1, $2, $3)",
		fileID, user.ID, "unknown") // TODO: Extract real IP from context
	if err != nil {
		log.Printf("Failed to record download: %v", err)
		// Don't fail the download if recording fails
	}

	// Generate download URL using S3
	cfg := config.Load()
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String(cfg.AWSRegion),
	})
	if err != nil {
		return "", fmt.Errorf("failed to create AWS session: %v", err)
	}

	svc := s3.New(sess)
	req, _ := svc.GetObjectRequest(&s3.GetObjectInput{
		Bucket: aws.String(cfg.S3Bucket),
		Key:    aws.String(fmt.Sprintf("uploads/%s", filehash)),
	})

	// Generate a presigned URL valid for 1 hour
	url, err := req.Presign(time.Hour)
	if err != nil {
		return "", fmt.Errorf("failed to generate download URL: %v", err)
	}

	return url, nil
}

// Me returns the current authenticated user's information.
// This query provides access to the user's profile data including ID, username,
// email, and role. It requires authentication and returns the user information
// from the JWT token context.
//
// This is commonly used by client applications to display current user information
// and determine user permissions based on their role.
//
// Returns the authenticated User object with profile information.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var userModel model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		user.ID,
	).Scan(&userModel.ID, &userModel.Username, &userModel.Email, &userModel.Role)

	if err != nil {
		return nil, fmt.Errorf("user not found: %v", err)
	}

	return &userModel, nil
}

// ListUsers is the resolver for the listUsers field.
// ListUsers returns a list of users accessible to the current user.
// This query provides user information for sharing and collaboration features.
// Regular users can see all users in the system for sharing purposes, while
// maintaining appropriate privacy controls.
//
// The returned user list can be used for user selection in sharing dialogs
// and collaboration features.
//
// Returns a slice of User objects accessible to the current user.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: ListUsers - listUsers"))
}

// ListAllUsers is the resolver for the listAllUsers field.
// ListAllUsers returns all users in the system (admin only).
// This query provides complete user information for administrative purposes.
// Only users with 'admin' role can access this endpoint, which returns
// comprehensive user data for system management.
//
// This is typically used in admin panels for user management, role assignment,
// and system monitoring activities.
//
// Returns a slice of all User objects in the system.
// Returns error if user lacks admin privileges or database query fails.
func (r *queryResolver) ListAllUsers(ctx context.Context) ([]*model.User, error) {
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return nil, fmt.Errorf("admin privileges required: %v", err)
	}

	rows, err := r.DB.Query(ctx, "SELECT id, username, email, COALESCE(role, 'user') FROM users ORDER BY username")
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %v", err)
	}
	defer rows.Close()

	var users []*model.User
	for rows.Next() {
		var user model.User
		err := rows.Scan(&user.ID, &user.Username, &user.Email, &user.Role)
		if err != nil {
			return nil, fmt.Errorf("failed to scan user: %v", err)
		}
		users = append(users, &user)
	}
	fmt.Println("ListAllUsers called, returning users:", users)
	return users, nil
}

// ListFiles is the resolver for the listFiles field.
// ListFiles returns files within a specific folder or root directory.
// This query provides a listing of files accessible to the current user within
// the specified folder. If folderID is nil, it returns files in the root directory.
//
// The query respects file ownership and sharing permissions - users can see their own
// files and files that have been shared with them. The results include file metadata
// such as name, size, type, and timestamps.
//
// Parameters:
//   - folderID: ID of the folder to list files from (nil for root)
//
// Returns a slice of File objects in the specified folder.
// Returns error if user lacks access to the folder or database query fails.
func (r *queryResolver) ListFiles(ctx context.Context, folderID *string) ([]*model.File, error) {
	// Get authenticated user
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	query := `SELECT id, filename, filetype, filesize, filehash, is_public, is_public_shared, 
	public_share_enabled_at, public_share_enabled_by, created_at, owner_id FROM files WHERE owner_id = $1`
	args := []interface{}{user.ID}

	if folderID != nil {
		query += " AND folder_id = $2"
		args = append(args, *folderID)
	} else {
		// When no folder is specified, only show files that don't belong to any folder
		query += " AND folder_id IS NULL"
	}

	query += " ORDER BY created_at DESC"

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to list files: %v", err)
	}
	defer rows.Close()

	var files []*model.File
	for rows.Next() {
		var file model.File
		var createdAt time.Time
		var publicShareEnabledAt *time.Time
		var publicShareEnabledByID *string
		var fileOwnerID string
		err := rows.Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash,
			&file.IsPublic, &file.IsPublicShared, &publicShareEnabledAt, &publicShareEnabledByID,
			&createdAt, &fileOwnerID)
		if err != nil {
			return nil, fmt.Errorf("failed to scan file: %v", err)
		}

		// Convert timestamp to string
		file.CreatedAt = createdAt.Format(time.RFC3339)

		// Handle public share timestamp
		if publicShareEnabledAt != nil {
			enabledAtStr := publicShareEnabledAt.Format(time.RFC3339)
			file.PublicShareEnabledAt = &enabledAtStr
		}

		// Generate filepath (S3 key or URL)
		file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

		// Get owner information
		var owner model.User
		err = r.DB.QueryRow(ctx,
			"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
			fileOwnerID,
		).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)
		if err != nil {
			return nil, fmt.Errorf("failed to get owner: %v", err)
		}
		file.Owner = &owner

		// Get public share enabled by user info if applicable
		if publicShareEnabledByID != nil {
			var enabledByUser model.User
			err = r.DB.QueryRow(ctx,
				"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
				*publicShareEnabledByID,
			).Scan(&enabledByUser.ID, &enabledByUser.Username, &enabledByUser.Email, &enabledByUser.Role)
			if err == nil {
				file.PublicShareEnabledBy = &enabledByUser
			}
		}

		files = append(files, &file)
	}

	return files, nil
}

// GetFile is the resolver for the getFile field.
// GetFile retrieves detailed information about a specific file.
// This query returns comprehensive file metadata including ownership, sharing status,
// file properties, and access permissions. Users can only access files they own
// or files that have been shared with them.
//
// The returned file object includes all metadata necessary for file operations
// such as downloading, sharing, or modifying properties.
//
// Parameters:
//   - fileID: Unique identifier of the file to retrieve
//
// Returns the File object with complete metadata.
// Returns error if user lacks access to the file, file doesn't exist, or database query fails.
func (r *queryResolver) GetFile(ctx context.Context, fileID string) (*model.File, error) {
	var file model.File
	var createdAt time.Time
	var ownerID string
	err := r.DB.QueryRow(ctx,
		`SELECT f.id, f.filename, f.filetype, f.filesize, f.filehash, f.is_public, f.created_at, f.owner_id
		 FROM files f WHERE f.id = $1`,
		fileID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &ownerID)

	if err != nil {
		return nil, fmt.Errorf("file not found: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get owner information
	var owner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		ownerID,
	).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)

	if err != nil {
		return nil, fmt.Errorf("failed to get owner: %v", err)
	}

	file.Owner = &owner

	return &file, nil
}

// SearchFiles is the resolver for the searchFiles field.
// SearchFiles performs advanced search across files with multiple filter criteria.
// This query provides powerful search capabilities including text search, file type filtering,
// size ranges, date ranges, uploader filtering, and folder scoping. Results include
// search facets for refining queries and pagination support for large result sets.
//
// The search respects user permissions - only files the user owns or has access to
// will appear in results. The query supports full-text search on file names and
// metadata, with additional filtering options for precise results.
//
// Parameters:
//   - query: Text search query for file names (optional)
//   - mimeTypes: Filter by specific MIME types (optional)
//   - sizeMin/sizeMax: File size range filter in bytes (optional)
//   - dateFrom/dateTo: File creation date range filter (optional)
//   - uploaderName: Filter by uploader username (optional)
//   - folderID: Restrict search to specific folder (optional)
//   - sortBy: Sort field (name, size, date, etc.) (optional)
//   - sortDirection: Sort direction (asc/desc) (optional)
//   - limit/offset: Pagination parameters (optional)
//
// Returns SearchResult with files, facets, and pagination info.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) SearchFiles(ctx context.Context, query *string, mimeTypes []string, sizeMin *int32, sizeMax *int32, dateFrom *string, dateTo *string, uploaderName *string, folderID *string, sortBy *string, sortDirection *string, limit *int32, offset *int32) (*model.SearchResult, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("user not authenticated: %v", err)
	}

	// Set defaults
	if limit == nil || *limit <= 0 || *limit > 100 {
		defaultLimit := int32(50)
		limit = &defaultLimit
	}
	if offset == nil || *offset < 0 {
		defaultOffset := int32(0)
		offset = &defaultOffset
	}
	if sortBy == nil {
		defaultSort := "created_at"
		sortBy = &defaultSort
	}
	if sortDirection == nil {
		defaultDirection := "DESC"
		sortDirection = &defaultDirection
	}

	// Build search query with conditions
	var conditions []string
	var args []interface{}
	argIndex := 1

	// Base security condition - user can only see their files, shared files, or public files
	conditions = append(conditions, fmt.Sprintf("(f.owner_id = $%d OR f.is_public = true OR EXISTS(SELECT 1 FROM file_shares fs WHERE fs.file_id = f.id AND fs.shared_with = $%d))", argIndex, argIndex))
	args = append(args, user.ID)
	argIndex++

	// Filename search
	if query != nil && *query != "" {
		conditions = append(conditions, fmt.Sprintf("f.filename ILIKE $%d", argIndex))
		args = append(args, "%"+*query+"%")
		argIndex++
	}

	// MIME type filter
	if len(mimeTypes) > 0 {
		var mimeConditions []string
		for _, mimeType := range mimeTypes {
			if mimeType != "" {
				mimeConditions = append(mimeConditions, fmt.Sprintf("f.filetype ILIKE $%d", argIndex))
				args = append(args, mimeType)
				argIndex++
			}
		}
		if len(mimeConditions) > 0 {
			conditions = append(conditions, "("+strings.Join(mimeConditions, " OR ")+")")
		}
	}

	// Size range filter
	if sizeMin != nil && *sizeMin > 0 {
		conditions = append(conditions, fmt.Sprintf("f.filesize >= $%d", argIndex))
		args = append(args, *sizeMin)
		argIndex++
	}
	if sizeMax != nil && *sizeMax > 0 {
		conditions = append(conditions, fmt.Sprintf("f.filesize <= $%d", argIndex))
		args = append(args, *sizeMax)
		argIndex++
	}

	// Date range filter
	if dateFrom != nil && *dateFrom != "" {
		conditions = append(conditions, fmt.Sprintf("f.created_at >= $%d", argIndex))
		args = append(args, *dateFrom)
		argIndex++
	}
	if dateTo != nil && *dateTo != "" {
		conditions = append(conditions, fmt.Sprintf("f.created_at <= $%d", argIndex))
		args = append(args, *dateTo+" 23:59:59")
		argIndex++
	}

	// Uploader name filter
	if uploaderName != nil && *uploaderName != "" {
		conditions = append(conditions, fmt.Sprintf("u.username ILIKE $%d", argIndex))
		args = append(args, "%"+*uploaderName+"%")
		argIndex++
	}

	// Folder filter
	if folderID != nil && *folderID != "" {
		if *folderID == "root" {
			conditions = append(conditions, "f.folder_id IS NULL")
		} else {
			conditions = append(conditions, fmt.Sprintf("f.folder_id = $%d", argIndex))
			args = append(args, *folderID)
			argIndex++
		}
	}

	// Validate sort field
	validSortFields := map[string]string{
		"filename":   "f.filename",
		"filesize":   "f.filesize",
		"created_at": "f.created_at",
		"filetype":   "f.filetype",
	}
	sortField, exists := validSortFields[*sortBy]
	if !exists {
		sortField = "f.created_at"
	}

	// Validate sort direction
	direction := "DESC"
	if *sortDirection == "ASC" || *sortDirection == "asc" {
		direction = "ASC"
	}

	// Build main query
	whereClause := "WHERE " + strings.Join(conditions, " AND ")

	mainQuery := fmt.Sprintf(`
		SELECT f.id, f.filename, f.filetype, f.filesize, f.filehash,
			   f.is_public, f.is_public_shared, f.public_share_enabled_at, f.created_at, f.owner_id,
			   u.username, u.email, u.role,
			   fo.id as folder_id, fo.name as folder_name,
			   pseu.username as public_share_enabled_by_username
		FROM files f
		JOIN users u ON f.owner_id = u.id
		LEFT JOIN folders fo ON f.folder_id = fo.id
		LEFT JOIN users pseu ON f.public_share_enabled_by = pseu.id
		%s
		ORDER BY %s %s
		LIMIT $%d OFFSET $%d
	`, whereClause, sortField, direction, argIndex, argIndex+1)

	args = append(args, *limit, *offset)

	// Execute main query
	rows, err := r.DB.Query(ctx, mainQuery, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to search files: %v", err)
	}
	defer rows.Close()

	var files []*model.File
	for rows.Next() {
		var file model.File
		var owner model.User
		var createdAt time.Time
		var publicShareEnabledAt *time.Time
		var folderID *string
		var folderName *string
		var publicShareEnabledByUsername *string

		err := rows.Scan(
			&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash,
			&file.IsPublic, &file.IsPublicShared, &publicShareEnabledAt, &createdAt, &owner.ID,
			&owner.Username, &owner.Email, &owner.Role,
			&folderID, &folderName, &publicShareEnabledByUsername,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan file: %v", err)
		}

		// Set timestamps
		file.CreatedAt = createdAt.Format(time.RFC3339)
		if publicShareEnabledAt != nil {
			timeStr := publicShareEnabledAt.Format(time.RFC3339)
			file.PublicShareEnabledAt = &timeStr
		}

		// Generate filepath from filehash
		file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

		// Set owner
		file.Owner = &owner

		// Set folder if exists
		if folderID != nil && folderName != nil {
			file.Folder = &model.Folder{
				ID:   *folderID,
				Name: *folderName,
			}
		}

		// Set public share enabled by user if exists
		if publicShareEnabledByUsername != nil {
			file.PublicShareEnabledBy = &model.User{
				Username: *publicShareEnabledByUsername,
			}
		}

		files = append(files, &file)
	}

	// Get total count
	countQuery := fmt.Sprintf(`
		SELECT COUNT(*)
		FROM files f
		JOIN users u ON f.owner_id = u.id
		LEFT JOIN folders fo ON f.folder_id = fo.id
		%s
	`, whereClause)

	var totalCount int32
	err = r.DB.QueryRow(ctx, countQuery, args[:len(args)-2]...).Scan(&totalCount)
	if err != nil {
		return nil, fmt.Errorf("failed to get total count: %v", err)
	}

	// Generate facets for better search experience

	facets, err := r.generateSearchFacets(ctx, conditions, args[:len(args)-2])
	if err != nil {
		// Don't fail the whole query if facets fail
		facets = &model.SearchFacets{
	    MimeTypes:   []*model.MimeTypeFacet{},
		Uploaders:   []*model.UploaderFacet{},
		SizeBuckets: []*model.SizeBucketFacet{},
	}
}

	hasMore := int32(*offset)+int32(len(files)) < totalCount

	return &model.SearchResult{
		Files:      files,
		TotalCount: totalCount,
		HasMore:    hasMore,
		Facets:     facets,
	}, nil
}

// ListSharedFiles is the resolver for the listSharedFiles field.
// ListSharedFiles returns all files that have been shared with the current user.
// This query provides access to files that other users have explicitly shared,
// showing the sharing details including permissions and the user who shared each file.
//
// The results include both read-only and read-write shared files, with appropriate
// permission indicators. This is typically used to display a "Shared with me" view
// in file management interfaces.
//
// Returns a slice of FileShares objects containing file and sharing metadata.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) ListSharedFiles(ctx context.Context) ([]*model.FileShares, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	rows, err := r.DB.Query(ctx,
		`SELECT id, file_id, shared_with, permission, shared_by 
		 FROM file_shares 
		 WHERE shared_with = $1 OR shared_by = $1`,
		user.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to list shared files: %v", err)
	}
	defer rows.Close()

	var shares []*model.FileShares
	for rows.Next() {
		var share model.FileShares
		var fileID, sharedWithID, sharedByID string
		err := rows.Scan(&share.ID, &fileID, &sharedWithID, &share.Permission, &sharedByID)
		if err != nil {
			return nil, fmt.Errorf("failed to scan share: %v", err)
		}

		// Get file information using the fileID variable
		var file model.File
		var createdAt time.Time
		var fileOwnerID string
		err = r.DB.QueryRow(ctx,
			"SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id FROM files WHERE id = $1",
			fileID,
		).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerID)
		if err != nil {
			continue
		}

		file.CreatedAt = createdAt.Format(time.RFC3339)
		file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

		// Get file owner information
		var fileOwner model.User
		err = r.DB.QueryRow(ctx,
			"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
			fileOwnerID,
		).Scan(&fileOwner.ID, &fileOwner.Username, &fileOwner.Email, &fileOwner.Role)
		if err != nil {
			continue
		}
		file.Owner = &fileOwner

		// Get shared with user information
		var sharedWith model.User
		err = r.DB.QueryRow(ctx,
			"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
			sharedWithID,
		).Scan(&sharedWith.ID, &sharedWith.Username, &sharedWith.Email, &sharedWith.Role)
		if err != nil {
			continue
		}

		// Get shared by user information
		var sharedBy model.User
		err = r.DB.QueryRow(ctx,
			"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
			sharedByID,
		).Scan(&sharedBy.ID, &sharedBy.Username, &sharedBy.Email, &sharedBy.Role)
		if err != nil {
			continue
		}

		// Populate the share object with all details
		share.File = &file
		share.SharedWith = &sharedWith
		share.SharedBy = &sharedBy

		shares = append(shares, &share)
	}

	return shares, nil
}

// ListPublicFiles is the resolver for the listPublicFiles field.
// ListPublicFiles returns all publicly accessible files in the system.
// This query provides a listing of files that have been made public by their owners,
// allowing any authenticated user to discover and download them. The results include
// file metadata and download statistics.
//
// Public files are those explicitly shared publicly by their owners and appear in
// this global listing. This supports use cases like public file repositories or
// shared resource libraries.
//
// Returns a slice of PublicFile objects with metadata and download counts.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) ListPublicFiles(ctx context.Context) ([]*model.PublicFile, error) {
	_, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	rows, err := r.DB.Query(ctx,
		`SELECT f.id, f.filename, f.filetype, f.filesize, f.created_at, f.public_share_enabled_at, f.owner_id,
				u.id, u.username, u.email, u.role,
				COALESCE(download_stats.download_count, 0) as download_count
		 FROM files f
		 JOIN users u ON f.owner_id = u.id
		 LEFT JOIN (
			SELECT file_id, COUNT(*) as download_count 
			FROM file_downloads 
			GROUP BY file_id
		 ) download_stats ON f.id = download_stats.file_id
		 WHERE f.is_public_shared = TRUE
		 ORDER BY f.public_share_enabled_at DESC`)
	if err != nil {
		return nil, fmt.Errorf("failed to list public files: %v", err)
	}
	defer rows.Close()

	var publicFiles []*model.PublicFile
	for rows.Next() {
		var publicFile model.PublicFile
		var owner model.User
		var createdAt, publicSharedAt time.Time

		err := rows.Scan(
			&publicFile.ID, &publicFile.Filename, &publicFile.Filetype, &publicFile.Filesize,
			&createdAt, &publicSharedAt,
			&owner.ID, &owner.ID, &owner.Username, &owner.Email, &owner.Role,
			&publicFile.DownloadCount,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan public file: %v", err)
		}

		publicFile.CreatedAt = createdAt.Format(time.RFC3339)
		publicFile.PublicSharedAt = publicSharedAt.Format(time.RFC3339)
		publicFile.Owner = &owner

		publicFiles = append(publicFiles, &publicFile)
	}

	return publicFiles, nil
}

// GetFileDownloadStats is the resolver for the getFileDownloadStats field.
// GetFileDownloadStats retrieves download statistics for a specific file.
// This query returns detailed download analytics including total download count
// and individual download records with timestamps and user information.
//
// Only file owners can access download statistics for their files. This information
// is useful for understanding file usage patterns and popular content.
//
// Parameters:
//   - fileID: Unique identifier of the file to get statistics for
//
// Returns FileDownloadStats with download count and detailed records.
// Returns error if user lacks permission, file doesn't exist, or database query fails.
func (r *queryResolver) GetFileDownloadStats(ctx context.Context, fileID string) (*model.FileDownloadStats, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Check if the user owns the file or is admin
	var ownerID string
	err = r.DB.QueryRow(ctx, "SELECT owner_id FROM files WHERE id = $1", fileID).Scan(&ownerID)
	if err != nil {
		return nil, fmt.Errorf("file not found: %v", err)
	}

	if ownerID != user.ID && user.Role != "admin" {
		return nil, fmt.Errorf("permission denied: you can only view stats for your own files")
	}

	// Get total download count
	var totalDownloads int32
	err = r.DB.QueryRow(ctx,
		"SELECT COUNT(*) FROM file_downloads WHERE file_id = $1",
		fileID).Scan(&totalDownloads)
	if err != nil {
		return nil, fmt.Errorf("failed to get download count: %v", err)
	}

	// Get detailed download records
	rows, err := r.DB.Query(ctx,
		`SELECT fd.id, fd.downloaded_at, fd.ip_address, fd.downloaded_by,
				u.id, u.username, u.email, u.role
		 FROM file_downloads fd
		 LEFT JOIN users u ON fd.downloaded_by = u.id
		 WHERE fd.file_id = $1
		 ORDER BY fd.downloaded_at DESC
		 LIMIT 100`, // Limit to most recent 100 downloads
		fileID)
	if err != nil {
		return nil, fmt.Errorf("failed to get download history: %v", err)
	}
	defer rows.Close()

	var downloads []*model.FileDownload
	for rows.Next() {
		var download model.FileDownload
		var downloadedAt time.Time
		var downloadedByID *string
		var userID, username, email, role *string

		err := rows.Scan(
			&download.ID, &downloadedAt, &download.IPAddress, &downloadedByID,
			&userID, &username, &email, &role,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan download record: %v", err)
		}

		download.DownloadedAt = downloadedAt.Format(time.RFC3339)
		if downloadedByID != nil && userID != nil && username != nil && email != nil && role != nil {
			download.DownloadedBy = &model.User{
				ID:       *userID,
				Username: *username,
				Email:    *email,
				Role:     *role,
			}
		}

		downloads = append(downloads, &download)
	}

	return &model.FileDownloadStats{
		TotalDownloads: totalDownloads,
		Downloads:      downloads,
	}, nil
}

// GetDownloadURL is the resolver for the getDownloadUrl field.
// GetDownloadURL generates a secure, time-limited download URL for a file.
// This query creates a pre-signed URL that allows direct download from S3 storage
// while maintaining security and access controls. The URL expires after a short
// period to prevent unauthorized sharing.
//
// Users can only generate download URLs for files they own or have access to.
// Each download request is logged for audit and analytics purposes.
//
// Parameters:
//   - fileID: Unique identifier of the file to download
//
// Returns a secure download URL string.
// Returns error if user lacks access, file doesn't exist, or S3 operation fails.
func (r *queryResolver) GetDownloadURL(ctx context.Context, fileID string) (string, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return "", fmt.Errorf("user not authenticated: %v", err)
	}

	// Query file and get the storage key from content table
	var filename, filehash string
	var isPublic bool
	var ownerID string
	query := `
		SELECT f.filename, f.filehash, f.is_public, f.owner_id
		FROM files f
		WHERE f.id = $1 AND (f.owner_id = $2 OR f.is_public = true OR 
			EXISTS(SELECT 1 FROM file_shares fs WHERE fs.file_id = f.id AND fs.shared_with = $2))
	`

	err = r.DB.QueryRow(ctx, query, fileID, user.ID).Scan(
		&filename, &filehash, &isPublic, &ownerID,
	)
	if err != nil {
		return "", fmt.Errorf("file not found or access denied: %v", err)
	}

	// Get storage key from content table
	var storageKey string
	err = r.DB.QueryRow(ctx, "SELECT storage_key FROM content WHERE sha256 = $1", filehash).Scan(&storageKey)
	if err != nil {
		return "", fmt.Errorf("content not found: %v", err)
	}

	// Create AWS session and S3 client
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String("eu-north-1"),
	})
	if err != nil {
		return "", fmt.Errorf("failed to create AWS session: %v", err)
	}
	s3Client := s3.New(sess)

	// Generate a presigned URL for download (valid for 1 hour)
	req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
		Bucket: aws.String("go-drive-v2"),
		Key:    aws.String(storageKey),
	})

	downloadURL, err := req.Presign(1 * time.Hour)
	if err != nil {
		return "", fmt.Errorf("failed to generate download URL: %v", err)
	}

	// Log file download audit event
	go r.AuditLogger.LogFileDownload(context.Background(), user.ID, fileID, filename, nil)

	return downloadURL, nil
}

// ListFolders is the resolver for the listFolders field.
// ListFolders returns folders within a specified parent folder or root directory.
// This query provides folder hierarchy navigation by listing subfolders within
// a given parent folder. If parentID is nil, it returns root-level folders.
//
// Users can only see folders they own, maintaining privacy and access control.
// The results include folder metadata such as name, creation date, and ownership.
//
// Parameters:
//   - parentID: ID of the parent folder to list subfolders from (nil for root)
//
// Returns a slice of Folder objects within the specified parent.
// Returns error if user lacks access to the parent folder or database query fails.
func (r *queryResolver) ListFolders(ctx context.Context, parentID *string) ([]*model.Folder, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	query := "SELECT id, name, created_at FROM folders WHERE owner_id = $1"
	args := []interface{}{user.ID}

	if parentID != nil {
		query += " AND parent_id = $2"
		args = append(args, *parentID)
	} else {
		query += " AND parent_id IS NULL"
	}

	query += " ORDER BY name"

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to list folders: %v", err)
	}
	defer rows.Close()

	var folders []*model.Folder
	for rows.Next() {
		var folder model.Folder
		var createdAt time.Time
		err := rows.Scan(&folder.ID, &folder.Name, &createdAt)
		if err != nil {
			return nil, fmt.Errorf("failed to scan folder: %v", err)
		}

		// Convert timestamp to string
		folder.CreatedAt = createdAt.Format(time.RFC3339)

		// Set owner information (we already have it from auth context)
		folder.Owner = &model.User{
			ID:       user.ID,
			Username: user.Username,
			Email:    user.Email,
			Role:     user.Role,
		}

		folders = append(folders, &folder)
	}

	return folders, nil
}

// GetUserStatistics is the resolver for the getUserStatistics field.
// GetUserStatistics returns storage and usage statistics for the current user.
// This query provides comprehensive analytics about the user's file storage usage,
// including total files, storage consumption, deduplication savings, and sharing activity.
//
// Statistics include file count, original vs. actual storage used (showing space
// saved through deduplication), and sharing metrics. This information helps users
// understand their storage utilization and sharing patterns.
//
// Returns UserStatistics with storage usage and sharing metrics.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) GetUserStatistics(ctx context.Context) (*model.UserStatistics, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Get user's file count
	var fileCount int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM files WHERE owner_id = $1", user.ID).Scan(&fileCount)
	if err != nil {
		return nil, fmt.Errorf("failed to get file count: %v", err)
	}

	// Get original total size (sum of all individual file sizes, ignoring deduplication)
	var originalSize int
	err = r.DB.QueryRow(ctx, "SELECT COALESCE(SUM(filesize), 0) FROM files WHERE owner_id = $1", user.ID).Scan(&originalSize)
	if err != nil {
		return nil, fmt.Errorf("failed to get original file sizes: %v", err)
	}

	// Get actual storage used (accounting for deduplication)
	var totalUsed int
	err = r.DB.QueryRow(ctx, "SELECT COALESCE(SUM(size_bytes), 0) FROM content WHERE sha256 IN (SELECT DISTINCT filehash FROM files WHERE owner_id = $1)", user.ID).Scan(&totalUsed)
	if err != nil {
		return nil, fmt.Errorf("failed to get storage usage: %v", err)
	}

	// Calculate savings from deduplication
	savingsBytes := originalSize - totalUsed
	savingsPercentage := float64(0)
	if originalSize > 0 {
		savingsPercentage = (float64(savingsBytes) / float64(originalSize)) * 100
	}

	// Get shared files count (files shared by this user)
	var totalSharedFiles int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM file_shares WHERE shared_by = $1", user.ID).Scan(&totalSharedFiles)
	if err != nil {
		return nil, fmt.Errorf("failed to get shared files count: %v", err)
	}

	// Get received shares count (files shared with this user)
	var totalReceivedShares int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM file_shares WHERE shared_with = $1", user.ID).Scan(&totalReceivedShares)
	if err != nil {
		return nil, fmt.Errorf("failed to get received shares count: %v", err)
	}

	return &model.UserStatistics{
		TotalUsed:           int32(totalUsed),           // Actual storage used (with deduplication)
		OriginalSize:        int32(originalSize),        // Sum of all individual file sizes
		SavingsBytes:        int32(savingsBytes),        // Space saved through deduplication
		SavingsPercentage:   savingsPercentage,
		FileCount:           int32(fileCount),
		TotalSharedFiles:    int32(totalSharedFiles),
		TotalReceivedShares: int32(totalReceivedShares),
	}, nil
}

// GetAdminStatistics is the resolver for the getAdminStatistics field.
// GetAdminStatistics returns system-wide statistics and metrics (admin only).
// This query provides comprehensive system analytics including total users,
// files, storage usage, public file metrics, and top downloaded files.
//
// Only users with 'admin' role can access these system-wide statistics.
// The data includes storage efficiency metrics, public sharing statistics,
// and download analytics useful for system monitoring and capacity planning.
//
// Returns AdminStatistics with system-wide metrics and analytics.
// Returns error if user lacks admin privileges or database query fails.
func (r *queryResolver) GetAdminStatistics(ctx context.Context) (*model.AdminStatistics, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Check if user is admin
	if user.Role != "admin" {
		return nil, fmt.Errorf("admin access required")
	}

	// Get total users
	var totalUsers int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM users").Scan(&totalUsers)
	if err != nil {
		return nil, fmt.Errorf("failed to get user count: %v", err)
	}

	// Get total files
	var totalFiles int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM files").Scan(&totalFiles)
	if err != nil {
		return nil, fmt.Errorf("failed to get file count: %v", err)
	}

	// Get total storage (sum of all file sizes)
	var totalStorage int
	err = r.DB.QueryRow(ctx, "SELECT COALESCE(SUM(filesize), 0) FROM files").Scan(&totalStorage)
	if err != nil {
		return nil, fmt.Errorf("failed to get storage usage: %v", err)
	}

	// Calculate storage savings from deduplication
	// Compare total logical size vs actual unique storage size
	var actualStorageUsed int
	err = r.DB.QueryRow(ctx, `
		SELECT COALESCE(SUM(filesize), 0) 
		FROM (
			SELECT DISTINCT ON (filehash) filesize 
			FROM files 
			WHERE filehash IS NOT NULL
		) unique_files`).Scan(&actualStorageUsed)
	if err != nil {
		// If query fails, assume no deduplication savings
		actualStorageUsed = totalStorage
	}
	
	totalSavings := totalStorage - actualStorageUsed
	if totalSavings < 0 {
		totalSavings = 0
	}

	// Get total public files
	var totalPublicFiles int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM files WHERE is_public_shared = TRUE").Scan(&totalPublicFiles)
	if err != nil {
		return nil, fmt.Errorf("failed to get public file count: %v", err)
	}

	// Get total public downloads
	var totalPublicDownloads int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM file_downloads").Scan(&totalPublicDownloads)
	if err != nil {
		return nil, fmt.Errorf("failed to get download count: %v", err)
	}

	// Get top downloaded files
	topFilesRows, err := r.DB.Query(ctx,
		`SELECT f.id, f.filename, f.public_share_enabled_at,
				u.id, u.username, u.email, u.role,
				COUNT(fd.id) as download_count
		 FROM files f
		 JOIN users u ON f.owner_id = u.id
		 LEFT JOIN file_downloads fd ON f.id = fd.file_id
		 WHERE f.is_public_shared = TRUE
		 GROUP BY f.id, f.filename, f.public_share_enabled_at, u.id, u.username, u.email, u.role
		 ORDER BY download_count DESC
		 LIMIT 5`)
	if err != nil {
		return nil, fmt.Errorf("failed to get top files: %v", err)
	}
	defer topFilesRows.Close()

	var topDownloadedFiles []*model.PublicFileStats
	for topFilesRows.Next() {
		var fileStats model.PublicFileStats
		var owner model.User
		var publicSharedAt *time.Time
		var downloadCount int

		err := topFilesRows.Scan(
			&fileStats.ID, &fileStats.Filename, &publicSharedAt,
			&owner.ID, &owner.Username, &owner.Email, &owner.Role,
			&downloadCount,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan top file: %v", err)
		}

		fileStats.DownloadCount = int32(downloadCount)
		fileStats.Owner = &owner
		
		if publicSharedAt != nil {
			fileStats.PublicSharedAt = publicSharedAt.Format(time.RFC3339)
		}

		topDownloadedFiles = append(topDownloadedFiles, &fileStats)
	}

	// Get recent downloads
	recentDownloadsRows, err := r.DB.Query(ctx,
		`SELECT fd.id, fd.downloaded_at, fd.ip_address, fd.downloaded_by,
				u.id, u.username, u.email, COALESCE(u.role, 'user')
		 FROM file_downloads fd
		 LEFT JOIN users u ON fd.downloaded_by = u.id
		 ORDER BY fd.downloaded_at DESC
		 LIMIT 10`)
	if err != nil {
		return nil, fmt.Errorf("failed to get recent downloads: %v", err)
	}
	defer recentDownloadsRows.Close()

	var recentDownloads []*model.FileDownload
	for recentDownloadsRows.Next() {
		var download model.FileDownload
		var downloadedAt time.Time
		var downloadedByID *string
		var userID, username, email, role *string

		err := recentDownloadsRows.Scan(
			&download.ID, &downloadedAt, &download.IPAddress, &downloadedByID,
			&userID, &username, &email, &role,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan recent download: %v", err)
		}

		download.DownloadedAt = downloadedAt.Format(time.RFC3339)

		// Set user info if available
		if downloadedByID != nil && userID != nil {
			download.DownloadedBy = &model.User{
				ID:       *userID,
				Username: *username,
				Email:    *email,
				Role:     *role,
			}
		}

		recentDownloads = append(recentDownloads, &download)
	}

	return &model.AdminStatistics{
		TotalUsers:           int32(totalUsers),
		TotalFiles:           int32(totalFiles),
		TotalStorage:         int32(totalStorage),
		TotalSavings:         int32(totalSavings),
		TotalPublicFiles:     int32(totalPublicFiles),
		TotalPublicDownloads: int32(totalPublicDownloads),
		TopDownloadedFiles:   topDownloadedFiles,
		RecentDownloads:      recentDownloads,
	}, nil
}

// GetAllFiles returns all files with uploader details for admin panel
// GetAllFiles returns all files in the system (admin only).
// This query provides complete file listing across all users for administrative
// purposes such as system monitoring, content moderation, and storage management.
//
// Only users with 'admin' role can access this comprehensive file listing.
// The results include files from all users with complete metadata.
//
// Returns a slice of all File objects in the system.
// Returns error if user lacks admin privileges or database query fails.
func (r *queryResolver) GetAllFiles(ctx context.Context) ([]*model.File, error) {
	rows, err := r.DB.Query(ctx, `
		SELECT f.id, f.filename, f.filehash, f.filetype, f.filesize, 
			   f.is_public, f.is_public_shared, f.public_share_enabled_at, f.created_at,
			   u.id as owner_id, u.username, u.email, u.role,
			   psu.id as public_share_by_id, psu.username as public_share_by_username,
			   psu.email as public_share_by_email, psu.role as public_share_by_role,
			   fo.id as folder_id, fo.name as folder_name
		FROM files f
		JOIN users u ON f.owner_id = u.id
		LEFT JOIN users psu ON f.public_share_enabled_by = psu.id
		LEFT JOIN folders fo ON f.folder_id = fo.id
		ORDER BY f.created_at DESC
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch all files: %v", err)
	}
	defer rows.Close()

	var files []*model.File
	for rows.Next() {
		var file model.File
		var owner model.User
		var publicShareEnabledBy *model.User
		var folder *model.Folder
		var createdAt, publicShareEnabledAt time.Time
		var publicShareEnabledAtPtr *time.Time
		var publicShareByID, publicShareByUsername, publicShareByEmail, publicShareByRole *string
		var folderID, folderName *string

		err := rows.Scan(
			&file.ID, &file.Filename, &file.Filehash, &file.Filetype, &file.Filesize,
			&file.IsPublic, &file.IsPublicShared, &publicShareEnabledAtPtr, &createdAt,
			&owner.ID, &owner.Username, &owner.Email, &owner.Role,
			&publicShareByID, &publicShareByUsername, &publicShareByEmail, &publicShareByRole,
			&folderID, &folderName,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan file: %v", err)
		}

		file.CreatedAt = createdAt.Format(time.RFC3339)
		file.Owner = &owner

		if publicShareEnabledAtPtr != nil {
			publicShareEnabledAt = *publicShareEnabledAtPtr
			formattedTime := publicShareEnabledAt.Format(time.RFC3339)
			file.PublicShareEnabledAt = &formattedTime
		}

		if publicShareByID != nil {
			publicShareEnabledBy = &model.User{
				ID:       *publicShareByID,
				Username: *publicShareByUsername,
				Email:    *publicShareByEmail,
				Role:     *publicShareByRole,
			}
			file.PublicShareEnabledBy = publicShareEnabledBy
		}

		if folderID != nil {
			folder = &model.Folder{
				ID:   *folderID,
				Name: *folderName,
			}
			file.Folder = folder
		}

		files = append(files, &file)
	}

	return files, nil
}

// GetAuditLogs is the resolver for the getAuditLogs field (Admin only).
// GetAuditLogs returns system audit logs with optional filtering (admin only).
// This query provides access to comprehensive audit trails for security monitoring,
// compliance, and system analysis. Supports filtering by user, action type,
// resource type, and pagination for large datasets.
//
// Only users with 'admin' role can access system-wide audit logs. The logs include
// all user actions, system events, and security-relevant activities with detailed
// metadata including timestamps, IP addresses, and user agents.
//
// Parameters:
//   - limit: Maximum number of log entries to return (optional)
//   - offset: Number of entries to skip for pagination (optional)
//   - userID: Filter by specific user ID (optional)
//   - action: Filter by action type (optional)
//   - resourceType: Filter by resource type (optional)
//
// Returns AuditLogConnection with logs, total count, and pagination info.
// Returns error if user lacks admin privileges or database query fails.
func (r *queryResolver) GetAuditLogs(ctx context.Context, limit *int32, offset *int32, userID *string, action *string, resourceType *string) (*model.AuditLogConnection, error) {
	// fmt.Printf("GetAuditLogs called\n")
	
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		// fmt.Printf("GetAuditLogs: authentication error: %v\n", err)
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// fmt.Printf("GetAuditLogs: user role = %s\n", user.Role)

	// Check if user is admin
	if user.Role != "admin" {
		fmt.Printf("GetAuditLogs: non-admin user trying to access\n")
		return nil, fmt.Errorf("admin access required")
	}

	// Set defaults
	if limit == nil {
		defaultLimit := int32(50)
		limit = &defaultLimit
	}
	if offset == nil {
		defaultOffset := int32(0)
		offset = &defaultOffset
	}

	// Build query with optional filters
	whereClause := "WHERE 1=1"
	args := []interface{}{}
	argIndex := 1

	if userID != nil {
		whereClause += fmt.Sprintf(" AND al.user_id = $%d", argIndex)
		args = append(args, *userID)
		argIndex++
	}
	if action != nil {
		whereClause += fmt.Sprintf(" AND al.action = $%d", argIndex)
		args = append(args, *action)
		argIndex++
	}
	if resourceType != nil {
		whereClause += fmt.Sprintf(" AND al.resource_type = $%d", argIndex)
		args = append(args, *resourceType)
		argIndex++
	}

	// Add limit and offset
	args = append(args, *limit+1, *offset) // +1 to check if there are more records

	query := fmt.Sprintf(`
		SELECT al.id, al.user_id, al.action, al.resource_type, al.resource_id, 
		       al.resource_name, al.details, al.ip_address, al.user_agent, al.created_at,
		       u.id, u.username, u.email, u.role
		FROM audit_logs al
		JOIN users u ON al.user_id = u.id
		%s
		ORDER BY al.created_at DESC
		LIMIT $%d OFFSET $%d
	`, whereClause, argIndex, argIndex+1)

	// fmt.Printf("GetAuditLogs: executing query: %s\n", query)
	// fmt.Printf("GetAuditLogs: args: %v\n", args)

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		// fmt.Printf("GetAuditLogs: query error: %v\n", err)
		return nil, fmt.Errorf("failed to get audit logs: %v", err)
	}
	defer rows.Close()

	var logs []*model.AuditLog
	rowCount := 0
	for rows.Next() {
		rowCount++
		// fmt.Printf("GetAuditLogs: processing row %d\n", rowCount)
		var log model.AuditLog
		var user model.User
		var createdAt time.Time
		var resourceID *string
		var resourceName, details, ipAddress, userAgent *string
		var userIDFromAudit string // for al.user_id

		err := rows.Scan(
			&log.ID, &userIDFromAudit, &log.Action, &log.ResourceType, &resourceID,
			&resourceName, &details, &ipAddress, &userAgent, &createdAt,
			&user.ID, &user.Username, &user.Email, &user.Role,
		)
		if err != nil {
			// fmt.Printf("GetAuditLogs: scan error on row %d: %v\n", rowCount, err)
			continue
		}

		// fmt.Printf("GetAuditLogs: scanned log ID: %s, action: %s\n", log.ID, log.Action)

		log.User = &user
		log.CreatedAt = createdAt.Format(time.RFC3339)
		if resourceID != nil {
			log.ResourceID = resourceID
		}
		if resourceName != nil {
			log.ResourceName = resourceName
		}
		if details != nil {
			log.Details = details
		}
		if ipAddress != nil {
			log.IPAddress = ipAddress
		}
		if userAgent != nil {
			log.UserAgent = userAgent
		}

		logs = append(logs, &log)
	}

	// fmt.Printf("GetAuditLogs: total logs found: %d\n", len(logs))

	// Check if there are more records
	hasMore := int32(len(logs)) > *limit
	if hasMore {
		logs = logs[:*limit] // Remove the extra record
	}

	// Get total count
	countQuery := fmt.Sprintf("SELECT COUNT(*) FROM audit_logs al %s", whereClause)
	var totalCount int
	err = r.DB.QueryRow(ctx, countQuery, args[:len(args)-2]...).Scan(&totalCount)
	if err != nil {
		return nil, fmt.Errorf("failed to get total count: %v", err)
	}

	// fmt.Printf("GetAuditLogs: returning %d logs, totalCount: %d, hasMore: %t\n", len(logs), totalCount, hasMore)

	return &model.AuditLogConnection{
		Logs:       logs,
		TotalCount: int32(totalCount),
		HasMore:    hasMore,
	}, nil
}

// GetUserAuditLogs is the resolver for the getUserAuditLogs field.
// GetUserAuditLogs returns audit logs for the current user's activities.
// This query provides users with visibility into their own actions and system
// interactions for transparency and security awareness. Includes pagination
// support for browsing through historical activities.
//
// Users can only access their own audit logs, ensuring privacy while providing
// transparency about their account activities. Logs include file operations,
// sharing actions, and authentication events.
//
// Parameters:
//   - limit: Maximum number of log entries to return (optional)
//   - offset: Number of entries to skip for pagination (optional)
//
// Returns AuditLogConnection with user's logs, total count, and pagination info.
// Returns error if user is not authenticated or database query fails.
func (r *queryResolver) GetUserAuditLogs(ctx context.Context, limit *int32, offset *int32) (*model.AuditLogConnection, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Set defaults
	if limit == nil {
		defaultLimit := int32(50)
		limit = &defaultLimit
	}
	if offset == nil {
		defaultOffset := int32(0)
		offset = &defaultOffset
	}

	query := `
		SELECT al.id, al.action, al.resource_type, al.resource_id, 
		       al.resource_name, al.details, al.ip_address, al.user_agent, al.created_at
		FROM audit_logs al
		WHERE al.user_id = $1
		ORDER BY al.created_at DESC
		LIMIT $2 OFFSET $3
	`

	rows, err := r.DB.Query(ctx, query, user.ID, *limit+1, *offset)
	if err != nil {
		return nil, fmt.Errorf("failed to get user audit logs: %v", err)
	}
	defer rows.Close()

	var logs []*model.AuditLog
	for rows.Next() {
		var log model.AuditLog
		var createdAt time.Time
		var resourceID *string
		var resourceName, details, ipAddress, userAgent *string

		err := rows.Scan(
			&log.ID, &log.Action, &log.ResourceType, &resourceID,
			&resourceName, &details, &ipAddress, &userAgent, &createdAt,
		)
		if err != nil {
			continue
		}

		log.User = &model.User{
			ID:       user.ID,
			Username: user.Username,
			Email:    user.Email,
			Role:     user.Role,
		}
		log.CreatedAt = createdAt.Format(time.RFC3339)
		if resourceID != nil {
			log.ResourceID = resourceID
		}
		if resourceName != nil {
			log.ResourceName = resourceName
		}
		if details != nil {
			log.Details = details
		}
		if ipAddress != nil {
			log.IPAddress = ipAddress
		}
		if userAgent != nil {
			log.UserAgent = userAgent
		}

		logs = append(logs, &log)
	}

	// Check if there are more records
	hasMore := int32(len(logs)) > *limit
	if hasMore {
		logs = logs[:*limit] // Remove the extra record
	}

	// Get total count for this user
	var totalCount int
	err = r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM audit_logs WHERE user_id = $1", user.ID).Scan(&totalCount)
	if err != nil {
		return nil, fmt.Errorf("failed to get total count: %v", err)
	}

	return &model.AuditLogConnection{
		Logs:       logs,
		TotalCount: int32(totalCount),
		HasMore:    hasMore,
	}, nil
}

// generateSearchFacets generates search facets for file search results.
// This helper function creates aggregated facet data that helps users refine their search queries.
// It analyzes the current search results to provide categorized counts for MIME types,
// file size ranges, and uploaders, enabling faceted search functionality.
//
// The function generates three types of facets:
// 1. MIME Type Facets: Groups files by content type categories (Images, Videos, Documents, etc.)
// 2. Size Bucket Facets: Creates size ranges with file counts for each range
// 3. Uploader Facets: Lists users who uploaded files matching the search criteria
//
// This data is typically used in search interfaces to show filter options with
// result counts, allowing users to narrow down their search results effectively.
//
// Parameters:
//   - conditions: SQL WHERE conditions from the main search query
//   - args: Query arguments corresponding to the conditions
//
// Returns SearchFacets object with categorized facet data.
// Returns error if database queries fail during facet generation.
func (r *queryResolver) generateSearchFacets(ctx context.Context, conditions []string, args []interface{}) (*model.SearchFacets, error) {
	whereClause := "WHERE " + strings.Join(conditions, " AND ")

	// MIME type facets
	mimeQuery := fmt.Sprintf(`
		SELECT
			CASE
				WHEN f.filetype LIKE 'image/%%' THEN 'Images'
				WHEN f.filetype LIKE 'video/%%' THEN 'Videos'
				WHEN f.filetype LIKE 'audio/%%' THEN 'Audio'
				WHEN f.filetype LIKE 'text/%%' THEN 'Text'
				WHEN f.filetype IN ('application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') THEN 'Documents'
				WHEN f.filetype LIKE 'application/%%' THEN 'Applications'
				ELSE 'Other'
			END as category,
			f.filetype,
			COUNT(*) as count
		FROM files f
		JOIN users u ON f.owner_id = u.id
		%s
		GROUP BY category, f.filetype
		ORDER BY count DESC
		LIMIT 20
	`, whereClause)

	mimeRows, err := r.DB.Query(ctx, mimeQuery, args...)
	if err != nil {
		return nil, err
	}
	defer mimeRows.Close()

	var mimeTypeFacets []*model.MimeTypeFacet
	for mimeRows.Next() {
		var facet model.MimeTypeFacet
		err := mimeRows.Scan(&facet.Category, &facet.Type, &facet.Count)
		if err != nil {
			continue
		}
		mimeTypeFacets = append(mimeTypeFacets, &facet)
	}

	// Uploader facets
	uploaderQuery := fmt.Sprintf(`
		SELECT u.username, u.id, COUNT(*) as count
		FROM files f
		JOIN users u ON f.owner_id = u.id
		%s
		GROUP BY u.username, u.id
		ORDER BY count DESC
		LIMIT 10
	`, whereClause)

	uploaderRows, err := r.DB.Query(ctx, uploaderQuery, args...)
	if err != nil {
		return nil, err
	}
	defer uploaderRows.Close()

	var uploaderFacets []*model.UploaderFacet
	for uploaderRows.Next() {
		var facet model.UploaderFacet
		err := uploaderRows.Scan(&facet.Username, &facet.UserID, &facet.Count)
		if err != nil {
			continue
		}
		uploaderFacets = append(uploaderFacets, &facet)
	}

	// Size bucket facets
	sizeQuery := fmt.Sprintf(`
		SELECT
			CASE
				WHEN f.filesize < 1048576 THEN 'Small (< 1MB)'
				WHEN f.filesize < 10485760 THEN 'Medium (1-10MB)'
				WHEN f.filesize < 104857600 THEN 'Large (10-100MB)'
				ELSE 'Huge (> 100MB)'
			END as range_label,
			CASE
				WHEN f.filesize < 1048576 THEN 0
				WHEN f.filesize < 10485760 THEN 1048576
				WHEN f.filesize < 104857600 THEN 10485760
				ELSE 104857600
			END as min_size,
			CASE
				WHEN f.filesize < 1048576 THEN 1048576
				WHEN f.filesize < 10485760 THEN 10485760
				WHEN f.filesize < 104857600 THEN 104857600
				ELSE NULL
			END as max_size,
			COUNT(*) as count
		FROM files f
		JOIN users u ON f.owner_id = u.id
		%s
		GROUP BY range_label, min_size, max_size
		ORDER BY min_size
	`, whereClause)

	sizeRows, err := r.DB.Query(ctx, sizeQuery, args...)
	if err != nil {
		return nil, err
	}
	defer sizeRows.Close()

	var sizeBucketFacets []*model.SizeBucketFacet
	for sizeRows.Next() {
		var facet model.SizeBucketFacet
		var maxSize *int32
		err := sizeRows.Scan(&facet.Range, &facet.Min, &maxSize, &facet.Count)
		if err != nil {
			continue
		}
		facet.Max = maxSize
		sizeBucketFacets = append(sizeBucketFacets, &facet)
	}

	return &model.SearchFacets{
		MimeTypes:   mimeTypeFacets,
		Uploaders:   uploaderFacets,
		SizeBuckets: sizeBucketFacets,
	}, nil
}



// Mutation returns MutationResolver implementation.
// This method creates and returns a mutation resolver instance that handles
// all GraphQL mutation operations for the Balkan Drive system.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
// This method creates and returns a query resolver instance that handles
// all GraphQL query operations for the Balkan Drive system.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// mutationResolver implements the MutationResolver interface.
// It embeds the main Resolver struct to access database connections,
// audit logging, and other shared dependencies for mutation operations.
type mutationResolver struct{ *Resolver }

// queryResolver implements the QueryResolver interface.
// It embeds the main Resolver struct to access database connections,
// audit logging, and other shared dependencies for query operations.
type queryResolver struct{ *Resolver }
