package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	jwt "github.com/golang-jwt/jwt/v5"
	pgx "github.com/jackc/pgx/v5"
	"github.com/rival231/Balkan_Drive/graph/model"
	"github.com/rival231/Balkan_Drive/internal/config"
	"github.com/rival231/Balkan_Drive/internal/middleware"
	"golang.org/x/crypto/bcrypt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string) (*model.AuthPayload, error) {
	// Hash password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}

	// Create user with default role
	user := &model.User{Role: "user"}
	err = r.DB.QueryRow(ctx,
		"INSERT INTO users (username, email, password, role, created_at) VALUES ($1, $2, $3, $4, NOW()) RETURNING id, username, email",
		username, email, string(hashedPassword), "user").Scan(&user.ID, &user.Username, &user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %v", err)
	}

	// Create JWT token with proper claims
	cfg := config.Load()
	claims := &middleware.Claims{
		UserID:   user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(cfg.JWTSecret))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}

	return &model.AuthPayload{
		Token: tokenString,
		User:  user,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	var user model.User
	var hashedPassword string

	err := r.DB.QueryRow(ctx,
		"SELECT id, username, email, password, COALESCE(role, 'user') FROM users WHERE email = $1",
		email).Scan(&user.ID, &user.Username, &user.Email, &hashedPassword, &user.Role)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Verify password
	if err := bcrypt.CompareHashAndPassword([]byte(hashedPassword), []byte(password)); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Create JWT token
	cfg := config.Load()
	claims := &middleware.Claims{
		UserID:   user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(24 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(cfg.JWTSecret))
	if err != nil {
		return nil, fmt.Errorf("failed to sign token: %v", err)
	}

	return &model.AuthPayload{
		Token: tokenString,
		User:  &user,
	}, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, oldPassword string, newPassword string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	var currentPassword string
	err = r.DB.QueryRow(ctx, "SELECT password FROM users WHERE id = $1", user.ID).Scan(&currentPassword)
	if err != nil {
		return false, fmt.Errorf("user not found: %v", err)
	}

	// Verify old password
	if err := bcrypt.CompareHashAndPassword([]byte(currentPassword), []byte(oldPassword)); err != nil {
		return false, fmt.Errorf("invalid old password")
	}

	// Hash new password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(newPassword), bcrypt.DefaultCost)
	if err != nil {
		return false, fmt.Errorf("failed to hash password: %v", err)
	}

	// Update password
	_, err = r.DB.Exec(ctx, "UPDATE users SET password = $1 WHERE id = $2", string(hashedPassword), user.ID)
	if err != nil {
		return false, fmt.Errorf("failed to update password: %v", err)
	}

	return true, nil
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, filename string, filetype string, filePath string, filesize int32, isPublic bool, file graphql.Upload) (*model.UploadIntent, error) {
	// Get authenticated user
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	hash := sha256.New()
	var fileContent bytes.Buffer
	teeReader := io.TeeReader(file.File, &fileContent)
	if _, err := io.Copy(hash, teeReader); err != nil {
		return nil, fmt.Errorf("failed to read file content: %v", err)
	}
	filehash := hex.EncodeToString(hash.Sum(nil))
	actualFileSize := int64(fileContent.Len())
	var refCount int
	var existingStorageKey string
	err = r.DB.QueryRow(ctx,
		`SELECT ref_count, storage_key FROM content WHERE sha256 = $1`,
		filehash,
	).Scan(&refCount, &existingStorageKey)

	contentExists := err == nil
	if err != nil && err != pgx.ErrNoRows {
		return nil, fmt.Errorf("failed to check content: %v", err)
	}
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String("eu-north-1"),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create AWS session: %v", err)
	}
	s3Client := s3.New(sess)
	var storageKey string
	var uploadURL string
	if contentExists {
		storageKey = existingStorageKey
		_, err = r.DB.Exec(ctx,
			`UPDATE content SET ref_count = ref_count + 1 WHERE sha256 = $1`,
			filehash,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to update ref_count: %v", err)
		}
		req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
			Bucket: aws.String("go-drive-v2"),
			Key:    aws.String(storageKey),
		})
		uploadURL, err = req.Presign(15 * time.Minute)
		if err != nil {
			return nil, fmt.Errorf("failed to presign download URL: %v", err)
		}
	} else {
		storageKey = "uploads/" + filehash
		_, err = s3Client.PutObject(&s3.PutObjectInput{
			Bucket:      aws.String("go-drive-v2"),
			Key:         aws.String(storageKey),
			Body:        bytes.NewReader(fileContent.Bytes()),
			ContentType: aws.String(filetype),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to upload file to S3: %v", err)
		}
		req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
			Bucket: aws.String("go-drive-v2"),
			Key:    aws.String(storageKey),
		})
		uploadURL, err = req.Presign(15 * time.Minute)
		if err != nil {
			return nil, fmt.Errorf("failed to presign download URL: %v", err)
		}
		_, err = r.DB.Exec(ctx,
			`INSERT INTO content (sha256, storage_key, size_bytes, ref_count, created_at)
             VALUES ($1, $2, $3, $4, NOW())`,
			filehash, storageKey, actualFileSize, 1,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to insert content: %v", err)
		}
	}
	var fileRecord model.File
	err = r.DB.QueryRow(ctx,
		`INSERT INTO files (filename, filetype, filesize, filehash, is_public, owner_id, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, NOW())
         RETURNING id, filename, filetype, filesize, filehash, is_public`,
		filename, filetype, actualFileSize, filehash, isPublic, user.ID,
	).Scan(
		&fileRecord.ID,
		&fileRecord.Filename,
		&fileRecord.Filetype,
		&fileRecord.Filesize,
		&fileRecord.Filehash,
		&fileRecord.IsPublic,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to insert file: %v", err)
	}
	return &model.UploadIntent{
		UploadURL:   uploadURL,
		UploadToken: filehash,
	}, nil
}

// CompleteUpload is the resolver for the completeUpload field.
func (r *mutationResolver) CompleteUpload(ctx context.Context, uploadToken string) (*model.File, error) {
	// Find file by hash (uploadToken)
	var file model.File
	var createdAt time.Time
	var ownerID string
	err := r.DB.QueryRow(ctx,
		`SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id
		 FROM files WHERE filehash = $1 ORDER BY created_at DESC LIMIT 1`,
		uploadToken,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &ownerID)

	if err != nil {
		return nil, fmt.Errorf("upload not found: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get owner information
	var owner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		ownerID,
	).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)

	if err != nil {
		return nil, fmt.Errorf("failed to get owner: %v", err)
	}

	file.Owner = &owner

	return &file, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, fileID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if user owns the file
	var ownerID, filehash string
	err = r.DB.QueryRow(ctx, "SELECT owner_id, filehash FROM files WHERE id = $1", fileID).Scan(&ownerID, &filehash)
	if err != nil {
		return false, fmt.Errorf("file not found: %v", err)
	}

	if ownerID != user.ID {
		return false, fmt.Errorf("you can only delete your own files")
	}

	// Delete file record
	_, err = r.DB.Exec(ctx, "DELETE FROM files WHERE id = $1", fileID)
	if err != nil {
		return false, fmt.Errorf("failed to delete file: %v", err)
	}

	// Decrement reference count and delete from S3 if no more references
	var refCount int
	var storageKey string
	err = r.DB.QueryRow(ctx,
		"UPDATE content SET ref_count = ref_count - 1 WHERE sha256 = $1 RETURNING ref_count, storage_key",
		filehash,
	).Scan(&refCount, &storageKey)

	if err != nil {
		return false, fmt.Errorf("failed to update content: %v", err)
	}

	// If no more references, delete from S3 and content table
	if refCount <= 0 {
		cfg := config.Load()

		// Delete from S3
		sess, _ := session.NewSession(&aws.Config{
			Region: aws.String(cfg.AWSRegion),
		})
		s3Client := s3.New(sess)

		_, err = s3Client.DeleteObject(&s3.DeleteObjectInput{
			Bucket: aws.String(cfg.S3Bucket),
			Key:    aws.String(storageKey),
		})
		if err != nil {
			// Log error but don't fail the operation
			fmt.Printf("Failed to delete from S3: %v\n", err)
		}

		// Delete content record
		_, err = r.DB.Exec(ctx, "DELETE FROM content WHERE sha256 = $1", filehash)
		if err != nil {
			return false, fmt.Errorf("failed to delete content: %v", err)
		}
	}

	return true, nil
}

// ChangeVisibility is the resolver for the changeVisibility field.
func (r *mutationResolver) ChangeVisibility(ctx context.Context, fileID string, isPublic bool) (*model.File, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// Check ownership and update
	var file model.File
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`UPDATE files SET is_public = $1 WHERE id = $2 AND owner_id = $3 
		 RETURNING id, filename, filetype, filesize, filehash, is_public, created_at`,
		isPublic, fileID, user.ID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt)

	if err != nil {
		return nil, fmt.Errorf("failed to update file visibility: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Set owner information
	file.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &file, nil
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(ctx context.Context, fileID string, folderID *string) (*model.File, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var file model.File
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`UPDATE files SET folder_id = $1 WHERE id = $2 AND owner_id = $3 
		 RETURNING id, filename, filetype, filesize, filehash, is_public, created_at`,
		folderID, fileID, user.ID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt)

	if err != nil {
		return nil, fmt.Errorf("failed to move file: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Set owner information
	file.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &file, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string, parentID *string) (*model.Folder, error) {
	folder := &model.Folder{}
	var createdAt time.Time
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}
	err = r.DB.QueryRow(ctx,
		"INSERT INTO folders (name, parent_id, owner_id, created_at) VALUES ($1, $2, $3, NOW()) RETURNING id, name, created_at",
		name, parentID, user.ID,
	).Scan(&folder.ID, &folder.Name, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create folder: %v", err)
	}

	// Convert timestamp to string
	folder.CreatedAt = createdAt.Format(time.RFC3339)

	// Set owner information
	folder.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return folder, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, folderID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	// Check if folder exists and user owns it
	var ownerID string
	err = r.DB.QueryRow(ctx, "SELECT owner_id FROM folders WHERE id = $1", folderID).Scan(&ownerID)
	if err != nil {
		return false, fmt.Errorf("folder not found: %v", err)
	}

	if ownerID != user.ID {
		return false, fmt.Errorf("you can only delete your own folders")
	}

	// Check if folder has files or subfolders
	var fileCount, subfolderCount int
	r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM files WHERE folder_id = $1", folderID).Scan(&fileCount)
	r.DB.QueryRow(ctx, "SELECT COUNT(*) FROM folders WHERE parent_id = $1", folderID).Scan(&subfolderCount)

	if fileCount > 0 || subfolderCount > 0 {
		return false, fmt.Errorf("folder is not empty")
	}

	_, err = r.DB.Exec(ctx, "DELETE FROM folders WHERE id = $1", folderID)
	if err != nil {
		return false, fmt.Errorf("failed to delete folder: %v", err)
	}

	return true, nil
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, folderID string, newName string) (*model.Folder, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var folder model.Folder
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`UPDATE folders SET name = $1 WHERE id = $2 AND owner_id = $3 
		 RETURNING id, name, created_at`,
		newName, folderID, user.ID,
	).Scan(&folder.ID, &folder.Name, &createdAt)

	if err != nil {
		return nil, fmt.Errorf("failed to rename folder: %v", err)
	}

	// Convert timestamp to string
	folder.CreatedAt = createdAt.Format(time.RFC3339)

	// Set owner information
	folder.Owner = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &folder, nil
}

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(ctx context.Context, fileID string, userID string, relationship string) (*model.FileShares, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var share model.FileShares
	err = r.DB.QueryRow(ctx,
		`INSERT INTO file_shares (file_id, shared_with_id, permission, shared_by_id, created_at)
		 VALUES ($1, $2, $3, $4, NOW())
		 RETURNING id`,
		fileID, userID, relationship, user.ID,
	).Scan(&share.ID)

	if err != nil {
		return nil, fmt.Errorf("failed to share file: %v", err)
	}

	// Populate the complete FileShares object
	share.Permission = relationship

	// Get the file information
	var file model.File
	var createdAt time.Time
	var fileOwnerID string
	err = r.DB.QueryRow(ctx,
		"SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerID)
	if err != nil {
		return nil, fmt.Errorf("failed to get file: %v", err)
	}

	file.CreatedAt = createdAt.Format(time.RFC3339)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get file owner information
	var fileOwner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		fileOwnerID,
	).Scan(&fileOwner.ID, &fileOwner.Username, &fileOwner.Email, &fileOwner.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get file owner: %v", err)
	}
	file.Owner = &fileOwner
	share.File = &file

	// Get the shared with user information
	var sharedWith model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		userID,
	).Scan(&sharedWith.ID, &sharedWith.Username, &sharedWith.Email, &sharedWith.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get shared with user: %v", err)
	}
	share.SharedWith = &sharedWith

	// Set the shared by user (current user)
	share.SharedBy = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &share, nil
}

// ShareFileByUsername is the resolver for the shareFileByUsername field.
func (r *mutationResolver) ShareFileByUsername(ctx context.Context, fileID string, username string, permission string) (*model.FileShares, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	// First, find the user by username
	var targetUserID string
	err = r.DB.QueryRow(ctx,
		"SELECT id FROM users WHERE username = $1",
		username,
	).Scan(&targetUserID)
	if err != nil {
		return nil, fmt.Errorf("user not found: %v", err)
	}

	// Check if the file exists and the current user owns it
	var fileOwnerID string
	err = r.DB.QueryRow(ctx,
		"SELECT owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&fileOwnerID)
	if err != nil {
		return nil, fmt.Errorf("file not found: %v", err)
	}

	if fileOwnerID != user.ID {
		return nil, fmt.Errorf("permission denied: you can only share your own files")
	}

	// Create the share
	var share model.FileShares
	err = r.DB.QueryRow(ctx,
		`INSERT INTO file_shares (file_id, shared_with_id, permission, shared_by_id, created_at)
		 VALUES ($1, $2, $3, $4, NOW())
		 RETURNING id`,
		fileID, targetUserID, permission, user.ID,
	).Scan(&share.ID)

	if err != nil {
		return nil, fmt.Errorf("failed to share file: %v", err)
	}

	// Populate the complete FileShares object
	share.Permission = permission

	// Get the file information
	var file model.File
	var createdAt time.Time
	var fileOwnerIDForFile string
	err = r.DB.QueryRow(ctx,
		"SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerIDForFile)
	if err != nil {
		return nil, fmt.Errorf("failed to get file: %v", err)
	}

	file.CreatedAt = createdAt.Format(time.RFC3339)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get file owner
	var fileOwner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		fileOwnerIDForFile,
	).Scan(&fileOwner.ID, &fileOwner.Username, &fileOwner.Email, &fileOwner.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get file owner: %v", err)
	}
	file.Owner = &fileOwner
	share.File = &file

	// Get the target user (shared with)
	var sharedWithUser model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		targetUserID,
	).Scan(&sharedWithUser.ID, &sharedWithUser.Username, &sharedWithUser.Email, &sharedWithUser.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to get shared user: %v", err)
	}
	share.SharedWith = &sharedWithUser

	// Set the current user as the one who shared
	share.SharedBy = &model.User{
		ID:       user.ID,
		Username: user.Username,
		Email:    user.Email,
		Role:     user.Role,
	}

	return &share, nil
}

// UnshareFile is the resolver for the unshareFile field.
func (r *mutationResolver) UnshareFile(ctx context.Context, fileID string, userID string) (bool, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %v", err)
	}

	_, err = r.DB.Exec(ctx,
		"DELETE FROM file_shares WHERE file_id = $1 AND shared_with_id = $2 AND shared_by_id = $3",
		fileID, userID, user.ID,
	)

	if err != nil {
		return false, fmt.Errorf("failed to unshare file: %v", err)
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var userModel model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		user.ID,
	).Scan(&userModel.ID, &userModel.Username, &userModel.Email, &userModel.Role)

	if err != nil {
		return nil, fmt.Errorf("user not found: %v", err)
	}

	return &userModel, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, userID string) (*model.User, error) {
	var user model.User
	err := r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		userID,
	).Scan(&user.ID, &user.Username, &user.Email, &user.Role)

	if err != nil {
		return nil, fmt.Errorf("user not found: %v", err)
	}

	return &user, nil
}

// GetFile is the resolver for the getFile field.
func (r *queryResolver) GetFile(ctx context.Context, fileID string) (*model.File, error) {
	var file model.File
	var createdAt time.Time
	var ownerID string
	err := r.DB.QueryRow(ctx,
		`SELECT f.id, f.filename, f.filetype, f.filesize, f.filehash, f.is_public, f.created_at, f.owner_id
		 FROM files f WHERE f.id = $1`,
		fileID,
	).Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &ownerID)

	if err != nil {
		return nil, fmt.Errorf("file not found: %v", err)
	}

	// Convert timestamp to string
	file.CreatedAt = createdAt.Format(time.RFC3339)

	// Generate filepath (this could be the S3 key or URL)
	file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

	// Get owner information
	var owner model.User
	err = r.DB.QueryRow(ctx,
		"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
		ownerID,
	).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)

	if err != nil {
		return nil, fmt.Errorf("failed to get owner: %v", err)
	}

	file.Owner = &owner

	return &file, nil
}

// ListFiles is the resolver for the listFiles field.
func (r *queryResolver) ListFiles(ctx context.Context, folder *string, isPublic *bool, ownerID *string) ([]*model.File, error) {
	// Get authenticated user
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	query := `SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id FROM files WHERE 1=1`
	args := []interface{}{}
	argCount := 0

	// Always filter by current user's files unless explicitly specified otherwise
	if ownerID != nil {
		// If ownerID is explicitly provided, use it (for admin functionality)
		argCount++
		query += fmt.Sprintf(" AND owner_id = $%d", argCount)
		args = append(args, *ownerID)
	} else {
		// Default: only show current user's files
		argCount++
		query += fmt.Sprintf(" AND owner_id = $%d", argCount)
		args = append(args, user.ID)
	}

	if folder != nil {
		argCount++
		query += fmt.Sprintf(" AND folder_id = $%d", argCount)
		args = append(args, *folder)
	} else {
		// When no folder is specified, only show files that don't belong to any folder
		query += " AND folder_id IS NULL"
	}

	if isPublic != nil {
		argCount++
		query += fmt.Sprintf(" AND is_public = $%d", argCount)
		args = append(args, *isPublic)
	}

	query += " ORDER BY created_at DESC"

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to list files: %v", err)
	}
	defer rows.Close()

	var files []*model.File
	for rows.Next() {
		var file model.File
		var createdAt time.Time
		var fileOwnerID string
		err := rows.Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerID)
		if err != nil {
			return nil, fmt.Errorf("failed to scan file: %v", err)
		}

		// Convert timestamp to string
		file.CreatedAt = createdAt.Format(time.RFC3339)

		// Generate filepath (S3 key or URL)
		file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

		// Get owner information
		var owner model.User
		err = r.DB.QueryRow(ctx,
			"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
			fileOwnerID,
		).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)
		if err != nil {
			return nil, fmt.Errorf("failed to get owner: %v", err)
		}
		file.Owner = &owner

		files = append(files, &file)
	}

	return files, nil
}

// SearchFiles is the resolver for the searchFiles field.
func (r *queryResolver) SearchFiles(ctx context.Context, query string) ([]*model.File, error) {
	searchQuery := `
		SELECT id, filename, filetype, filesize, filehash, is_public, created_at, owner_id 
		FROM files 
		WHERE filename ILIKE $1 
		ORDER BY created_at DESC
	`

	rows, err := r.DB.Query(ctx, searchQuery, "%"+query+"%")
	if err != nil {
		return nil, fmt.Errorf("failed to search files: %v", err)
	}
	defer rows.Close()

	var files []*model.File
	for rows.Next() {
		var file model.File
		var createdAt time.Time
		var fileOwnerID string
		err := rows.Scan(&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.Filehash, &file.IsPublic, &createdAt, &fileOwnerID)
		if err != nil {
			return nil, fmt.Errorf("failed to scan file: %v", err)
		}

		// Convert timestamp to string
		file.CreatedAt = createdAt.Format(time.RFC3339)

		// Generate filepath (S3 key or URL)
		file.Filepath = fmt.Sprintf("uploads/%s", file.Filehash)

		// Get owner information
		var owner model.User
		err = r.DB.QueryRow(ctx,
			"SELECT id, username, email, COALESCE(role, 'user') FROM users WHERE id = $1",
			fileOwnerID,
		).Scan(&owner.ID, &owner.Username, &owner.Email, &owner.Role)
		if err != nil {
			return nil, fmt.Errorf("failed to get owner: %v", err)
		}
		file.Owner = &owner

		files = append(files, &file)
	}

	return files, nil
}

// GetDownloadURL is the resolver for the getDownloadUrl field.
func (r *queryResolver) GetDownloadURL(ctx context.Context, fileID string) (string, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return "", fmt.Errorf("user not authenticated: %v", err)
	}

	// Query file and get the storage key from content table
	var filename, filehash string
	var isPublic bool
	var ownerID string
	query := `
		SELECT f.filename, f.filehash, f.is_public, f.owner_id
		FROM files f
		WHERE f.id = $1 AND (f.owner_id = $2 OR f.is_public = true OR 
			EXISTS(SELECT 1 FROM file_shares fs WHERE fs.file_id = f.id AND fs.shared_with = $2))
	`
	
	err = r.DB.QueryRow(ctx, query, fileID, user.ID).Scan(
		&filename, &filehash, &isPublic, &ownerID,
	)
	if err != nil {
		return "", fmt.Errorf("file not found or access denied: %v", err)
	}

	// Get storage key from content table
	var storageKey string
	err = r.DB.QueryRow(ctx, "SELECT storage_key FROM content WHERE sha256 = $1", filehash).Scan(&storageKey)
	if err != nil {
		return "", fmt.Errorf("content not found: %v", err)
	}

	// Create AWS session and S3 client
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String("eu-north-1"),
	})
	if err != nil {
		return "", fmt.Errorf("failed to create AWS session: %v", err)
	}
	s3Client := s3.New(sess)

	// Generate a presigned URL for download (valid for 1 hour)
	req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
		Bucket: aws.String("go-drive-v2"),
		Key:    aws.String(storageKey),
	})
	
	downloadURL, err := req.Presign(1 * time.Hour)
	if err != nil {
		return "", fmt.Errorf("failed to generate download URL: %v", err)
	}

	return downloadURL, nil
}

// ListSharedFiles is the resolver for the listSharedFiles field.
func (r *queryResolver) ListSharedFiles(ctx context.Context) ([]*model.FileShares, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	rows, err := r.DB.Query(ctx,
		`SELECT id, file_id, shared_with_id, permission, shared_by_id 
		 FROM file_shares 
		 WHERE shared_with_id = $1 OR shared_by_id = $1`,
		user.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to list shared files: %v", err)
	}
	defer rows.Close()

	var shares []*model.FileShares
	for rows.Next() {
		var share model.FileShares
		var fileID, sharedWithID, sharedByID string
		err := rows.Scan(&share.ID, &fileID, &sharedWithID, &share.Permission, &sharedByID)
		if err != nil {
			return nil, fmt.Errorf("failed to scan share: %v", err)
		}
		shares = append(shares, &share)
	}

	return shares, nil
}

// ListFolders is the resolver for the listFolders field.
func (r *queryResolver) ListFolders(ctx context.Context, parentID *string) ([]*model.Folder, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	query := "SELECT id, name, created_at FROM folders WHERE owner_id = $1"
	args := []interface{}{user.ID}

	if parentID != nil {
		query += " AND parent_id = $2"
		args = append(args, *parentID)
	} else {
		query += " AND parent_id IS NULL"
	}

	query += " ORDER BY name"

	rows, err := r.DB.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to list folders: %v", err)
	}
	defer rows.Close()

	var folders []*model.Folder
	for rows.Next() {
		var folder model.Folder
		var createdAt time.Time
		err := rows.Scan(&folder.ID, &folder.Name, &createdAt)
		if err != nil {
			return nil, fmt.Errorf("failed to scan folder: %v", err)
		}

		// Convert timestamp to string
		folder.CreatedAt = createdAt.Format(time.RFC3339)

		// Set owner information (we already have it from auth context)
		folder.Owner = &model.User{
			ID:       user.ID,
			Username: user.Username,
			Email:    user.Email,
			Role:     user.Role,
		}

		folders = append(folders, &folder)
	}

	return folders, nil
}

// StorageStats is the resolver for the storageStats field.
func (r *queryResolver) StorageStats(ctx context.Context) (*model.StorageStatistics, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %v", err)
	}

	var totalUsed, originalSize int64
	var fileCount int32

	// Get user's total storage usage (deduplicated)
	err = r.DB.QueryRow(ctx, `
		SELECT 
			COALESCE(SUM(DISTINCT c.size_bytes), 0) as total_used,
			COALESCE(SUM(f.filesize), 0) as original_size,
			COUNT(f.id) as file_count
		FROM files f
		JOIN content c ON f.filehash = c.sha256
		WHERE f.owner_id = $1
	`, user.ID).Scan(&totalUsed, &originalSize, &fileCount)

	if err != nil {
		return nil, fmt.Errorf("failed to get storage stats: %v", err)
	}

	savings := originalSize - totalUsed
	var savingsPercentage float64
	if originalSize > 0 {
		savingsPercentage = float64(savings) / float64(originalSize) * 100
	}

	return &model.StorageStatistics{
		TotalUsed:         int32(totalUsed),
		OriginalSize:      int32(originalSize),
		SavingsBytes:      int32(savings),
		SavingsPercentage: savingsPercentage,
		FileCount:         fileCount,
	}, nil
}

// AdminStats is the resolver for the adminStats field.
func (r *queryResolver) AdminStats(ctx context.Context) (*model.AdminStatistics, error) {
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return nil, fmt.Errorf("admin privileges required: %v", err)
	}

	var totalUsers, totalFiles int32
	var totalStorage, totalSavings int64

	// Get system-wide statistics
	err = r.DB.QueryRow(ctx, `
		SELECT 
			(SELECT COUNT(*) FROM users) as total_users,
			(SELECT COUNT(*) FROM files) as total_files,
			(SELECT COALESCE(SUM(size_bytes), 0) FROM content) as total_storage,
			(SELECT COALESCE(SUM(f.filesize) - SUM(DISTINCT c.size_bytes), 0) 
			 FROM files f JOIN content c ON f.filehash = c.sha256) as total_savings
	`).Scan(&totalUsers, &totalFiles, &totalStorage, &totalSavings)

	if err != nil {
		return nil, fmt.Errorf("failed to get admin stats: %v", err)
	}

	return &model.AdminStatistics{
		TotalUsers:   totalUsers,
		TotalFiles:   totalFiles,
		TotalStorage: int32(totalStorage),
		TotalSavings: int32(totalSavings),
	}, nil
}

// ListAllUsers is the resolver for the listAllUsers field.
func (r *queryResolver) ListAllUsers(ctx context.Context) ([]*model.User, error) {
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return nil, fmt.Errorf("admin privileges required: %v", err)
	}

	rows, err := r.DB.Query(ctx, "SELECT id, username, email, COALESCE(role, 'user') FROM users ORDER BY username")
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %v", err)
	}
	defer rows.Close()

	var users []*model.User
	for rows.Next() {
		var user model.User
		err := rows.Scan(&user.ID, &user.Username, &user.Email, &user.Role)
		if err != nil {
			return nil, fmt.Errorf("failed to scan user: %v", err)
		}
		users = append(users, &user)
	}

	return users, nil
}

// ListAllFiles is the resolver for the listAllFiles field.
func (r *queryResolver) ListAllFiles(ctx context.Context) ([]*model.File, error) {
	_, err := middleware.RequireAdmin(ctx)
	if err != nil {
		return nil, fmt.Errorf("admin privileges required: %v", err)
	}

	rows, err := r.DB.Query(ctx, `
		SELECT f.id, f.filename, f.filetype, f.filesize, f.is_public, f.filepath, f.filehash, 
		       f.created_at, f.user_id, u.username as owner_username
		FROM files f
		LEFT JOIN users u ON f.user_id = u.id
		ORDER BY f.created_at DESC
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to list all files: %v", err)
	}
	defer rows.Close()

	var files []*model.File
	for rows.Next() {
		var file model.File
		var ownerUsername *string
		var userID *string
		err := rows.Scan(
			&file.ID, &file.Filename, &file.Filetype, &file.Filesize, &file.IsPublic,
			&file.Filepath, &file.Filehash, &file.CreatedAt, &userID, &ownerUsername,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan file: %v", err)
		}

		// Set owner info if available
		if userID != nil && ownerUsername != nil {
			file.Owner = &model.User{
				ID:       *userID,
				Username: *ownerUsername,
			}
		}

		files = append(files, &file)
	}

	return files, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) GetDownloadUrl(ctx context.Context, fileID string) (string, error) {
	user, err := middleware.GetUserFromContext(ctx)
	if err != nil {
		return "", fmt.Errorf("authentication required: %v", err)
	}

	// Get file info and check ownership or public access
	var filehash string
	var isPublic bool
	var ownerID string
	err = r.DB.QueryRow(ctx,
		"SELECT filehash, is_public, owner_id FROM files WHERE id = $1",
		fileID,
	).Scan(&filehash, &isPublic, &ownerID)

	if err != nil {
		return "", fmt.Errorf("file not found: %v", err)
	}

	// Check if user has access (owner or public file)
	if ownerID != user.ID && !isPublic {
		// Check if file is shared with user
		var shareExists bool
		err = r.DB.QueryRow(ctx,
			"SELECT EXISTS(SELECT 1 FROM file_shares WHERE file_id = $1 AND shared_with_id = $2)",
			fileID, user.ID,
		).Scan(&shareExists)
		if err != nil || !shareExists {
			return "", fmt.Errorf("access denied: you don't have permission to download this file")
		}
	}

	// Generate S3 presigned download URL
	cfg := config.Load()
	sess := session.Must(session.NewSession(&aws.Config{
		Region: aws.String(cfg.AWSRegion),
	}))
	s3Client := s3.New(sess)

	storageKey := "uploads/" + filehash
	req, _ := s3Client.GetObjectRequest(&s3.GetObjectInput{
		Bucket: aws.String("go-drive-v2"),
		Key:    aws.String(storageKey),
	})

	downloadURL, err := req.Presign(15 * time.Minute) // 15 minute expiry
	if err != nil {
		return "", fmt.Errorf("failed to generate download URL: %v", err)
	}

	return downloadURL, nil
}
*/
